glib/src/translate.rs
This commit adds a free standing shortcut function `try_fom_glib` similar to `from_glib`.
Goes with https://github.com/gtk-rs/gir/pull/1135.
Used in [this `gstreamer-rs` PR](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/760).
```rust
pub fn end_of_stream(&self) -> Result<gst::FlowSuccess, gst::FlowError> {
unsafe {
gst::FlowSuccess::try_from_glib(ffi::gst_app_src_end_of_stream(self.to_glib_none().0))
}
}
```
```rust
pub fn end_of_stream(&self) -> Result<gst::FlowSuccess, gst::FlowError> {
unsafe { try_from_glib(ffi::gst_app_src_end_of_stream(self.to_glib_none().0)) }
}
```
=> translate/TryFromGlib: add shortcut func.

glib-macros/src/genum_derive.rs, glib/src/translate.rs
A defunct implementation could lead to inconsistencies or UB due to
a valid Rust value being constructed from an invalid or undefined
(aka None) C value.
Re-opened and updated to master from https://github.com/gtk-rs/gtk3-rs/pull/463
=> translate: make try_from_glib unsafe

cairo/src/context.rs, cairo/src/device.rs, cairo/src/enums.rs, cairo/src/pdf.rs, cairo/src/region.rs, gdk-pixbuf/src/pixbuf.rs, gio/src/converter.rs, gio/src/data_input_stream.rs, gio/src/dbus.rs, gio/src/dbus_connection.rs, gio/src/dbus_method_invocation.rs, gio/src/inet_address.rs, gio/src/input_stream.rs, gio/src/output_stream.rs, gio/src/pollable_input_stream.rs, gio/src/pollable_output_stream.rs, gio/src/socket.rs, gio/src/task.rs, glib/src/array.rs, glib/src/bytes.rs, glib/src/date.rs, glib/src/main_context_futures.rs, glib/src/object.rs, glib/src/source.rs, glib/src/string.rs, glib/src/value.rs, glib/src/value_array.rs, glib/src/variant.rs, glib/src/variant_dict.rs, pango/src/language.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/79.
I improved the previous python script:
<details>
```python
import os
import sys
IGNORE_C_FNS = ["_get_reference_count", "_status", "_free", "_destroy", "_unref"]
IGNORE_FNS = [
"deref", "deref_mut", "drop", "fmt", "clone", "to_value", "g_value_get_flags",
"g_value_set_flags", "get_type",
]
IGNORE_FNS_START = ["to_glib", "from_glib", "from_raw", "to_raw"]
def is_valid_name(s):
for c in s:
if not c.isalnum() and c != '_':
return False
for x in IGNORE_C_FNS:
if s.endswith(x):
return False
return True
def get_fn_name(s):
parts = s.split(" ")
x = 0
while x < len(parts) and parts[x] != "fn":
x += 1
x += 1
if x >= len(parts):
return None
fn_name = parts[x].split("<")[0].split("(")[0]
for x in IGNORE_FNS_START:
if fn_name.startswith(x): …
```
=> Add missing doc aliases

cairo/src/device.rs, cairo/src/font/font_face.rs, cairo/src/font/font_options.rs, cairo/src/font/scaled_font.rs, cairo/src/surface.rs, cairo/src/xcb.rs, gdk-pixbuf/src/pixbuf_animation_iter.rs, glib/src/array.rs, glib/src/byte_array.rs, glib/src/bytes.rs, glib/src/closure.rs, glib/src/date.rs, glib/src/enums.rs, glib/src/error.rs, glib/src/object.rs, glib/src/param_spec.rs, glib/src/source.rs, glib/src/string.rs, glib/src/thread_pool.rs, glib/src/translate.rs, glib/src/value.rs, glib/src/value_array.rs, glib/src/variant.rs, glib/src/variant_dict.rs, pango/src/attr_class.rs, pango/src/coverage.rs, pango/src/glyph.rs, pango/src/language.rs
Based on https://github.com/gtk-rs/checker/pull/27
=> Generate missing doc aliases for newtypes

.github/workflows/docs.yml
the gir-rustdoc looks for this env variable to define a list of releases on the index page. This would show a link to the versioned 0.10 docs
=> CI: add the 0.10 release to the index page

.github/workflows/CI.yml, glib-macros/src/utils.rs, tests/two-levels-glib-dependent/Cargo.toml, tests/two-levels-glib-dependent/README.md, tests/two-levels-glib-dependent/glib-dependent-dependent/Cargo.toml, tests/two-levels-glib-dependent/glib-dependent-dependent/src/lib.rs, tests/two-levels-glib-dependent/gstreamer/Cargo.toml, tests/two-levels-glib-dependent/gstreamer/src/lib.rs, tests/two-levels-glib-dependent/gtk/Cargo.toml, tests/two-levels-glib-dependent/gtk/src/lib.rs
When a crate includes 2 `glib` dependent known crates, the first known is
selected to prepend to `glib` in macros. If this first crate is optional
and not selected, it is not reachable and causes compilation error.
=> Fix glib re-export detection for macros

.github/workflows/docs.yml
so that the pre-docs step generates a link to the latest release correctly
=> CI docs: define releases env variable for all steps

glib-macros/src/lib.rs
=> glib-macros: add proc_macro_error attribute to clone

cairo/src/lib.rs, gdk-pixbuf/src/lib.rs, gio/src/lib.rs, glib/src/lib.rs, graphene/src/lib.rs, pango/src/lib.rs, pangocairo/src/lib.rs
Also adds minimum required version of the library to every crate doc.
=> Add minimal crate info

cairo/src/lib.rs
so that the link works properly for both stable/git docs
=> cairo docs: use mod for linking glib

stable/0.10/docs/cairo/index.html
otherwise the 0.10 cairo docs redirects the user to another docs source which isn't a great experience
=> stable docs: make cairo link to current glib

glib-macros/src/lib.rs, glib-macros/src/utils.rs
See https://github.com/gtk-rs/gtk-rs-core/issues/127 for details.
Crates checked locally:
- `gtk-rs-core`.
- `gtk3-rs`.
- `gtk4-rs`.
- `gstreamer-rs`.
- `gst-plugins-rs`.
Except for `clone!`, I didn't spot any explicit use of `glib::` in the other macros.
I think full CI should be launched on these crates after this is merged though.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/127
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/129
=> glib-macros: remove KNOWN_GLIB_EXPORTS

.github/workflows/docs.yml
because it's an ubuntu based image instead of a fedora one
=> CI: use apt instead of dnf

glib/src/signal.rs, glib/src/source.rs
I need to store the SourceId in a struct so it's automatically removed
on Drop. But I cannot do so as the SourceId does not implement Copy or
Clone and source_remove() consumes the SourceId.
=> glib: implement Clone on SourceId

glib/src/utils.rs
These are bindings for the GLib API available since GLib 2.16. They are also
exported in the `Uri` module available only when the v2_66 feature is enabled
though.
Fixes #164
=> uri: re-export URI parsing utilities

glib-macros/src/utils.rs
=> Remove unwanted warnings from the clone macro

glib/src/value.rs, glib/tests/value.rs
This more or less reverts https://github.com/gtk-rs/glib/commit/390ca3a2 ("Don't implement ToValue for Value").
Closes #4.
To be honest, I'm not 100% sure if this is the best way forward. The traits and trait bounds are really convoluted and hard to keep track of. For example, I don't know how well this works for `SendValue`. Let me know what you think.
=> Make stronger guarantees on `ToValue`

cairo/src/error.rs, cairo/src/lib.rs
Because it's really convenient.
=> Add cairo::Result type alias

cairo/src/utils.rs
Silence a clippy warning.
Or do we want to break API here and rename it "new"?
=> cairo: silence self_named_constructor

glib/src/boxed.rs, glib/src/shared.rs
Some unref APIs (vte_regex_unref) have return values. Ignore that to fix
compilation issues, and return void.
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
=> glib: ignore unref return value

glib/src/variant.rs
In ostree we compute `sha256(variant)` and expect this to be
in "normal form".  While this is a relatively obscure feature
it is public GLib API and trivial to expose.
The main benefit is this will help us drop a dependency on
`glib-sys` and move towards the re-export model from the 0.14
series.
=> glib/variant: Expose `g_variant_get_normal_form()`

cairo/src/image_surface.rs, cairo/src/lib.rs
This introduces a new function for `ImageSurface` which consumes the object, checks for exclusivity on the reference counter and returns a mutable slice of the raw data. Also added a minimal test case to verify.
Fixes #29
=> Add function to consume raw data of ImageSurface

glib/src/variant.rs
I was adding another variant of this (pun intended) and did
some searching to notice there's a better way than juggling
`(&*...)`.
=> variant: Use into_owned()

glib/src/variant.rs
A previous PR added `try_child_value()`; this adds a corresponding
`try_child_get()` which I think more users are going to want.
While we're here add `child_get()` which panics on any
unmet constraints.  In many cases such as e.g. iteration one
would be able to statically know that the bounds and types
are correct.
And another reason to add these is that as the `TODO` says,
in the future we can optimize these to avoid heap allocations
for intermediate `GVariant` references.
=> variant: Add more APIs to access typed children

glib/src/lib.rs, glib/src/variant.rs, glib/src/variant_iter.rs, glib/src/variant_type.rs
In ostree and rpm-ostree in particular we have quite a lot of
variants of type `as` (array of string).  Right now, accessing
those requires lots and lots of allocations.  Honestly, it's
mostly not truly performance sensitive, but I'd like to avoid
doing obviously silly things so that it doesn't become
a problem down the line.
We've had `.str()` for quite a while to access a variant of type `s`
without copying out the string data.  This extends that model to
variants of type `as` by allowing iteration over the values.
=> variant: Add an API to iterate over `as`

glib/src/variant.rs
We use this in ostree (and rpm-ostree) as we store variants in
big endian by default.
=> variant: Expose `g_variant_byteswap()`

gio/src/settings.rs
`g_settings_bind_with_mapping` doesn't support `G_SETTINGS_BIND_INVERT_BOOLEAN` and asserts it isn't in the flags.
To fix that, use `g_settings_bind` when both mapping functions are `None`.
(In gio `g_settings_bind` just calls `g_settings_bind_with_mapping`, and when `G_SETTINGS_BIND_INVERT_BOOLEAN` is passed it removes the flag and passes static mapping function to invert the value.)
=> gio: Fix behavior of `SettingsBindFlags::INVERT_BOOLEAN`

glib/src/variant_iter.rs
Fixes #244
Changing to the simpler `s as *const _` does not work, as it creates the opposite effect (glib fails to compile on x86 targets), so the double cast seems to be necessary.
I have confirmed that the glib crate with this patch compiles successfully on x86_64, i686, ppc64le, aarch64, armv7hl, and s390x.
=> glib: adapt to signed vs. unsigned libc::c_char to fix non-x86 builds

gio/src/subclass/application.rs, gio/src/subclass/input_stream.rs, gio/src/subclass/io_stream.rs, gio/src/subclass/output_stream.rs, glib/src/subclass/mod.rs, glib/src/subclass/types.rs
Also provides `parent_class_init()` and `parent_instance_init()` methods to make manual implementation a bit neater.
The implementation here is a bit of a mess, since specialization doesn't exist and `Self::default_class_init()` would error due to not being able to infer `T`, without using fully qualified syntax.
The Resulting API seems like an improvement though.
=> glib: Provide default implementations for `IsSubclassable` methods

gio/src/subclass/application.rs, gio/src/subclass/input_stream.rs, gio/src/subclass/io_stream.rs, gio/src/subclass/output_stream.rs, glib/src/subclass/mod.rs, glib/src/subclass/types.rs
Reverts gtk-rs/gtk-rs-core#241
This needs PRs for gtk3-rs and gtk4-rs to keep them buildable.
=> Revert "glib: Provide default implementations for `IsSubclassable` methods"

glib/src/variant_type.rs
And also implement it for `*mut _` in addition to `*const _`.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/248
=> Implement to_glib_full() for VariantType

gio/Gir.toml, gio/src/auto/list_store.rs
=> Ignore find_with_equal_func for ListStore until a suitable API is provided by the C library

examples/gio_task/file_size/ffi.rs
Return a GError on failure instead of unwrapping.
=> gio: fix gtask example

cairo/src/surface.rs, cairo/src/surface_macros.rs
The C function is technically (transfer none) as one must not call
destroy() on it to unreference it but instead
cairo_surface_unmap_image().
This was tried to be avoided in the Drop impl of MappedImageSurface but
not correctly, leading to assertions.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/265
=> cairo: Fix up reference counting in Surface::map_to_image()

glib/src/variant.rs
Before it tested the wrong variable
=> docs: Fix the examples for variants

glib/src/main_context_channel.rs
With edition 2021 the closures are only borrowing what they have to, so
here in this case it didn't actually borrow the helper as it was not
actually used inside the closure. With that, it was not dropped when the
main context channel was dropped and the main loop was never quit.
=> glib: Fix bug in main context channel test that caused it to deadlock

glib/src/value.rs
The current FromValue trait can't handle the FromValue<'static>
case as that means having to borrow self for 'static.
Needed for having a generic ObjectExt::property that would return T instead of Value. See #323
=> glib: add a Value::get_owned

cairo/src/font/font_options.rs, cairo/src/recording_surface.rs, glib/src/object.rs, glib/src/types.rs
It's a bit nonsensical and only bloats the API.
=> Remove Into<&str> trait bounds and directly use &str

cairo/sys/src/lib.rs
Fixes #123.
The important fix is that `cairo_bool_t` needs to be `repr(transparent)` - it doesn't work with `repr(C)` on s/390x otherwise.
Then, declare opaque types like `cairo_t` with the Rustonomicon's trick.
=> Fix #335 - repr(transparent) for cairo_bool_t; correct opaque types

glib/src/error.rs
It is handy if you need a str, for instance in a match where other
branches are already returning a str.
=> error: make message() public

glib-macros/src/gvariant_derive.rs, glib-macros/src/lib.rs, glib-macros/tests/test.rs, glib/src/lib.rs, glib/src/variant.rs
This allows storing arbitrary structs in `Variant`s as long as all their fields can be stored in `Variant`s.
=> glib-macros: Add a `Variant` trait derive macro

glib/src/variant.rs
These should deref to the contained type, not the underlying slice type.
Also get rid of all the `PartialEq` impls: having these is not too
useful, and there would be a lot more needed to cover all the special
cases similar to the ones the current ones cover.
=> glib: Fix `Deref` impls for `FixedSizeVariantArray`

pango/src/attr_list.rs
Noticed that when bumping librsvg to next gtk-rs stack https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/634
=> pango: take a generic attr in AttrList methods

examples/gio_task/file_size/imp.rs, gio/src/subclass/initable.rs, gio/src/task.rs, glib-macros/src/object_subclass_attribute.rs, glib-macros/tests/test.rs, glib/src/subclass/mod.rs, glib/src/subclass/object.rs, tests/two-levels-glib-dependent/glib-dependent-dependent/src/lib.rs
Use glib::Object if not specified.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/350
=> macros: make ParentType optional

gio/src/lib.rs
it only contains a impl Task
The reasoning comes from https://gtk-rs.org/gtk-rs-core/git/docs/gio/index.html#modules :-)
=> gio: don't expose task module

glib-macros/src/closure.rs, glib-macros/src/lib.rs, glib-macros/tests/test.rs, glib/src/closure.rs, glib/src/lib.rs, glib/src/object.rs
Fixes #19, probably also good enough for #23
I tried to copy the syntax of `clone!` as much as I could. This should be a convenient improvement on `connect_object` since this can take weak references on multiple objects in one call.
=> Add gclosure macro

glib/src/boxed.rs, glib/src/object.rs, glib/src/shared.rs
Especially for boxed types this is useful as it avoids an unnecessary
copy of the underlying value.
=> glib: Implement `FromValue` for references of object/shared/boxed types

glib/Gir.toml, glib/src/auto/functions.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/368
=> glib: Mark `g_get_user_special_dir()` return value as `nullable`

glib/src/collections.rs, glib/src/date.rs, glib/src/lib.rs
The `Iterator` implemention on the type itself directly consumes the
list so add another iterator that does not consume the list, and provide
an `iter()` method for getting it.
=> glib: Add API for non-destructive iteration over a `List` / `SList`

glib/src/param_spec.rs
Because otherwise you need to cast in ObjectImpl::properties
=> glib: return a ParamSpec for override methods

glib/src/source.rs
Based on https://github.com/gtk-rs/checker/pull/35.
=> Generate missing const doc aliases

glib/src/main_context_futures.rs
=> glib: make spawn*() return the SourceId

glib/Gir.toml, glib/src/auto/functions.rs
This avoids auto-generating a safe wrapper for `g_clear_error`.
Its NULL resetting logic isn't really useful in a safe Rust context.
=> glib/gir: ignore g_clear_error

glib/README.md
Along  with https://github.com/gtk-rs/gir/pull/1282, the warnings in the generated docs should be gone
=> glib: specify it's a Variant struct not a derive macro

glib/src/subclass/types.rs
So, I haven't tested it, but it doesn't use `unsafe` and it compiles, so I'm _pretty_ sure this just works
=> glib: add ObjectSubclassIsExt trait with impl_ method

pango/src/glyph_geometry.rs, pango/src/glyph_info.rs, pango/src/glyph_string.rs
From what I can understand about this API,  The GlyphGeometry objects inside of a GlyphString should be modifiable.
To make this work, its GlyphInfo's should not be a newly created vector, but rather a slice created from its internal pointer and length.
I believe this change brings it in line with how the API is meant to be used in C.
=> allow for the modifying GlyphInfo and GlyphGeometry

glib/src/signal.rs
Not particularly sure if this is useful since it can't be a strict requirement for closures, but it can give some consistency with the auto generated `connect` methods.
=> Implement ToValue on signal::Inhibit

glib-macros/src/boxed_derive.rs, glib-macros/src/downgrade_derive/enums.rs, glib-macros/src/downgrade_derive/fields.rs, glib-macros/src/downgrade_derive/structs.rs, glib-macros/src/enum_derive.rs, glib-macros/src/error_domain_derive.rs, glib-macros/src/flags_attribute.rs, glib-macros/src/object_interface_attribute.rs, glib-macros/src/object_subclass_attribute.rs, glib-macros/src/shared_boxed_derive.rs, glib-macros/src/variant_derive.rs
Just some cleanup, also adds use of `crate_ident_new` in a few places where it's missing. Technically this should also be done on the method calls at some point.
=> glib-macros: Use absolute paths in proc macros

glib-macros/src/object_subclass_attribute.rs, glib/src/object.rs, glib/src/subclass/types.rs
This could also be implemented by pulling `from_instance` out into a new trait, although that may break some uses of it
=> glib: Add a helper trait for getting an object from a wrapper or subclass

glib/src/boxed_inline.rs
otherwise bindings can't make use of it to create const like the GdkRGBA case.
=> boxed-inline: mark the phantom field as pub(crate)

examples/gio_task/file_size/mod.rs, gio/src/task.rs
Even with all the reccent improvements to the Task API, it is
still possible to bypass the requirements, for example by
casting LocalTask to Task, since they have the same underlying
GType.
At this point mark the constructors as unsafe and document
which invariants need to be manually esured by the callers.
The goal of this API is to enable callers to implement in
Rust APIs exposed to the C ffi which follow the glib
convention for async calls. Pure Rust applications should
probably use better abstractions to dispatch asynchronous
tasks.
=> gio: mark creating Task as unsafe and add public documentation

glib/src/error.rs, glib/src/value.rs
This facilitates conversion between potentially-fallible and infallible `Result<>`s, similar to some [std impls](https://doc.rust-lang.org/std/convert/enum.Infallible.html#impl-From%3CInfallible%3E)
=> glib: impl From<Infallible> for error types

.github/workflows/docs.yml
this is a workaround till we migrate the base image to something based on fedora
=> CI: publish docs directly to 0.15

glib/Gir.toml, glib/src/auto/functions.rs
Fixes: https://github.com/gtk-rs/gtk-rs-core/issues/489
=> Generate bindings for markup_escape_text

glib/src/variant.rs
The impls use the platform-specific byte representation for serialization, so they're `cfg`'d for `unix` and `windows`.
=> implement To/FromVariant for OS strings and paths

glib/src/object.rs, glib/src/subclass/object.rs
This is more convenient to use than passing a slice of string-trait
object tuples to the new function, and especially requires fewer &.
=> glib: Add an object builder

gio/src/gio_future.rs, glib/src/closure.rs, glib/src/lib.rs, glib/src/main_context_channel.rs, glib/src/main_context_futures.rs, glib/src/object.rs, glib/src/send_unique.rs, glib/src/source.rs, glib/src/thread_guard.rs
This is a preparation for https://github.com/gtk-rs/gir/issues/1305
=> glib: Provide `ThreadGuard` and `thread_id()` as public API

gio/src/initable.rs, gio/src/subclass/initable.rs
This corresponds to Object::with_type and it is needed when
the type is available only at runtime.
=> gio: add Initable::with_type

glib/src/bridged_logging.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/521
=> glib: Never pass `NULL` to `g_log_structured_standard()`

glib/src/lib.rs, glib/src/translate.rs, glib/src/types.rs, glib/src/value.rs
Resolves #508, enabling the storage and retrieval of pointers from a `Value`.
Integration with `g_pointer_type_register_static` mentioned in that issue is left for [a future expansion](https://github.com/arcnmx/gtk-rs-core/commit/pointer-subclass)
=> impl `StaticType` and `{From,To}Value` for `gpointer`

glib/src/value.rs, glib/src/variant.rs
Addresses the main part of #507 by providing explicit dynamic type variants of:
- `Variant::array_from_iter` -> `Variant::array_from_iter_with_type`
(a mouthful but consistent with other existing functions like `from_data_with_type_trusted`)
- `Variant::from_maybe` becomes `Variant::from_none` and `Variant::from_some`
- and adds an accessor: `Variant::as_maybe`
(panicking, should there be a `try_as_maybe`? should it return an `Option<Option<Variant>>` to be more in line with `Variant::as_variant`?)
- `Variant::is` -> `Variant::is_type`
(consider `is_of_type` instead?)
- `Value::is` -> `Value::is_type` (ditto)
- `Value::transform` -> `Value::transform_with_type`
(consider `transform_into`/`transform_to_type` instead?)
=> dynamic type function variants for Variants and Values

gio/src/task.rs
The g_task_return_value function does not take ownership of the input
GValue pointer, but just borrows it to make a copy:
https://developer-old.gnome.org/gio/unstable/GTask.html#g-task-return-value
The Rust caller should take care of the deallocation.
=> gtask: fix memory leak when calling g_task_return_value

glib/src/object.rs
This doesn't only check the type of the `Value` itself but if there's a
mismatch it grabs the contained object and does a check against the
concrete type of the object too.
This is necessary if e.g. the `Value` is initialized for a plain
`Object`, a `gtk::Widget` is stored inside it and it is tried to be
retrieved as `gtk::Widget` instead of `Object`.
----
CC @BrainBlasted @kavanmevada
=> glib: Add an `Object` specific value type checker

cairo/src/font/glyph.rs
it is not a u64, fixes the Windows CI breakage on gtk4-rs
=> cairo: fix Glyph::index type

glib/src/translate.rs
I am manually doing a hash table translation for
https://github.com/ostreedev/ostree/blob/4066b0ab4578add593c49448fb7553fdee656911/src/libostree/ostree-mutable-tree.c#L599
and went to look at this code and noticed it wasn't doing
the optimization I thought it would be.
=> translate: Pre-allocate Rust hashmap at correct size

glib-macros/src/variant_derive.rs, glib/src/variant.rs
The `Variant` constructors that take iterator arguments require passing in an owned `Variant`, even though only a temporary reference is actually required. `AsRef` is a nice way for these functions to accept either type (as well as a `Cow`, newtype wrappers, and more) for nicer ownership semantics, avoiding unnecessary clones, etc.
While generics could be used anywhere a `&Variant` is used in a constructor, iterators are the main pain point in comparison so I've only modified those here.
=> glib: impl AsRef<Variant> for Variant

glib/src/variant.rs, glib/src/variant_type.rs
This is a continuation of #519 (addressing #507) for creating a `DictEntry`-typed variant without static types (I missed it in my initial bug report, [even though it was present in the example](https://github.com/jf2048/glib-serde/blob/19e307a86786d385e655183c99212605e866d3dd/src/variant/mod.rs#L89)). The `VariantType` constructor is useful when working with these variants (for example in combination with `Variant::array_from_iter_with_type` to construct a vardict manually), so I included it along with the others.
=> Variant::from_dict_entry

glib/src/gobject/flags.rs, glib/src/param_spec.rs
This came out better than I expected.
=> define a corresponding `Builder` for each `ParamSpec`

glib/src/boxed.rs, glib/src/boxed_inline.rs, glib/src/shared.rs
While trying to use a generic shared wrapper I got this error:
```
warning: unnecessary parentheses around type                                                                           
--> /home/lollo/gtk-rs-core/glib/src/shared.rs:34:47                                                           
|                                                      
34  |               phantom: std::marker::PhantomData<($($($generic),+)?)>,                                            
|                                                 ^                 ^        
```
But then I found out that field is useless anyway, because the generic type is already used in the field above, so I've removed the phantom field.
=> remove problematic phantom in glib_shared_wrapper

gio/sys/Cargo.toml, glib/gobject-sys/Cargo.toml, glib/sys/Cargo.toml
Per https://github.com/gtk-rs/gtk-rs-core/pull/577#issuecomment-1058912597
Not sure this makes sense, we don't use odd version numbers for any of the other features?
=> Use glib 2.71 for minimum v2_72 pkg-config versions

glib/src/object.rs, glib/src/wrapper.rs, glib/tests/subclass_compiletest.rs, glib/tests/subclass_compiletest/01-auto-send-sync.rs, glib/tests/subclass_compiletest/02-no-auto-send-sync.rs, glib/tests/subclass_compiletest/02-no-auto-send-sync.stderr, glib/tests/subclass_compiletest/03-object-no-auto-send-sync.stderr, glib/tests/subclass_compiletest/04-auto-send-sync-with-send-sync-parent.rs, glib/tests/subclass_compiletest/05-no-auto-send-sync-with-non-send-sync-parent.rs, glib/tests/subclass_compiletest/05-no-auto-send-sync-with-non-send-sync-parent.stderr, glib/tests/subclass_compiletest/06-no-auto-send-sync-with-non-send-sync-ffi-parent.rs, glib/tests/subclass_compiletest/06-no-auto-send-sync-with-non-send-sync-ffi-parent.stderr
Previously a `Send+Sync` subclass of a `gtk::Widget` would automatically
be `Send+Sync` too, which is obviously not allowed.
To avoid this, also add the parent type as `PhantomData` to the wrapper
struct so that this is considered too.
Handle `glib::Object` specially here because while it is not `Send+Sync`
itself, subclasses of it can be `Send+Sync` just fine. The only reason
why `glib::Object` is not is because there are some subclasses that are
not and otherwise this could be circumvented by upcasting.
=> glib: Only auto-impl `Send+Sync` for subclasses if the parent type does

gio/Gir.toml, gio/src/auto/cancellable.rs, gio/src/cancellable.rs, gio/src/lib.rs, gio/src/prelude.rs
Fixes #240, this should work on any async runtime. The oneshot just gets triggered from whatever thread calls `cancel`.
`::connect` and `::disconnect` are maybe not the best choice for method names because they conflict with `ObjectExt`
=> More gio::Cancellable methods

glib-macros/src/lib.rs, glib/Gir.toml, glib/src/auto/enums.rs, glib/src/auto/mod.rs, glib/src/bridged_logging.rs, glib/src/gstring.rs, glib/src/lib.rs, glib/src/log.rs, glib/tests/structured_log.rs
Adds bindings for these functions:
- `glib::log_set_writer_func`
- `glib::log_structured_array`
- Requires a new `GStr` wrapper for a borrowed `GString`, so we can avoid copying the log keys.
- `glib::log_variant`
- `glib::log_writer_default`
- `glib::log_writer_format_fields`
- `glib::log_writer_journald`
- `glib::log_writer_standard_streams`
- `glib::log_writer_is_journald` - unix only
- `glib::log_writer_supports_color` - unix only
- `glib::log_writer_default_set_use_stderr`
- `glib::log_writer_default_would_drop`
And some new macros:
- `glib::gstr` - Turns a string literal into a `&'static GStr`, by appending a nul byte at compile time
- `glib::log_structured` - The main interface. From the docs:
```rust
log_structured!(
"test",
LogLevel::Debug,
{
// a normal string field
"MY_FIELD" …
```
=> Structured Logging

glib/src/log.rs
CI misses this but I'm seeing it locally
=> glib: Disable log_structured doc test before v2_50

glib/src/variant_type.rs
It already impl's `Display` and has a `new` constructor that parses the type description string, seems like a perfect fit!
Doc fixes also included because some of the fn descriptions were wrong.
=> impl FromStr for VariantType

glib/src/lib.rs, glib/src/variant_type.rs
Provide an Iterator over `VariantTy::first` and `VariantTy::next`.
It's a trivial implementation, but using the methods manually is silly and annoying.
=> glib: VariantTy tuple type iterator

glib-macros/tests/test.rs, glib/src/enums.rs
Also to skip things like `G_APPLICATION_FLAGS_NONE`, etc
=> glib: Don't serialize 0 value flags as variants

glib/src/variant.rs
This adds manual wrappers for the following functions:
- `g_variant_is_normal_form`
- `g_variant_is_object_path`
- `g_variant_is_signature`
It completes wrapping all the existing `g_variant_is_*` methods,
except for `g_variant_is_floating` which is not useful in Rust.
Closes: https://github.com/gtk-rs/gtk-rs-core/issues/622
=> glib/variant: add some more safe wrappers

glib/Gir.toml, glib/src/auto/functions.rs, glib/src/translate.rs, glib/src/utils.rs
These functions modify the passed in string in-place and either return it directly or return `NULL`. This kind of behaviour can only be handled manually.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/628
=> glib: Fix `mkdtemp()` and `mkdtemp_full()`

glib/src/translate.rs, glib/src/variant.rs
=> glib: Remove ending NUL when converting Variant to OsString.

glib/src/error.rs
This is handy when in a match you want to:
```
Err(e) if e.matches(IoErrorEnum::Cancelled) => ...
```
=> error: add `matches` method

glib/src/subclass/mod.rs, glib/src/subclass/object_impl_ref.rs
These provide strong/weak reference-counted wrappers around the
implementation type of GObject subclasses and can be used for passing
into closures, for example.
----
@bilelmoussaoui Do we know any places where this can be used in the gtk4-rs examples?
CC @piegamesde
=> glib: Add new `ObjectImplRef` and `ObjectImplWeakRef` types

gdk-pixbuf/Gir.toml, gdk-pixbuf/src/pixbuf.rs
This patch adds a section detailing the safety invariant one must hold
while using `Pixbuf::pixels` and also fixes a broken link.
---
Marking as draft as it depends on gtk-rs/gir#1341
=> gdk_pixbuf: Improve `Pixbuf::pixels` documentation

glib-macros/tests/test.rs, glib/src/object.rs
Adds support for watching a `Sync` object, adds a test for that, and adds safety docs as per #646
=> glib: WatchedObject improvements

glib-macros/src/lib.rs
=> glib-macros: Remove boxed_nullable and shared_boxed_nullable attribute for glib::Boxed

glib/src/object.rs, glib/src/subclass/object.rs
Some refactoring to improve code consistency and readability. Had to change an error message slightly (removed one word, "object"), but I don't think that's a problem because in other places that word wasn't used anyway. It's just more consistent now.
=> Set properties improvements

.github/workflows/image.yml, Dockerfile
Fixes part of #484
This is not using xlib/xft/rsvg, but we probably need those to build the gtk-rs images later? Or we can leave the gtk-rs images and not base them on this image? The image is already pretty large as-is, around 1.6GB on my system because of all the debug symbols. Another option is to maybe use `--buildtype release`
=> Port Dockerfile to fedora rawhide and use system deps from git

.github/workflows/image.yml, Dockerfile
Now that gdk-pixbuf is [updated](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/132), on my CI it successfully builds to completion and then fails when trying to upload the image, which is expected: https://github.com/jf2048/gtk-rs-core/runs/6414933753?check_suite_focus=true#step:3:12617
Also a few more fixes:
- don't use the checkout action, it's unnecessary because build-push-action also does a checkout
- fixes a [deprecation warning](https://github.com/jf2048/gtk-rs-core/runs/6341505238?check_suite_focus=true#step:4:10) about build-push-action@v1
=> Don't build gdk-pixbuf tests in the docker image

gio/Cargo.toml, gio/src/async_initable.rs, gio/src/initable.rs, gio/src/subclass/async_initable.rs, gio/src/subclass/initable.rs, gio/src/subclass/mod.rs
Fixes #22
Questions:
- Is it worth having both `init_async` and `init_future`? I think it would be fine with just `init_future`
- I made a lightweight alternative to `LocalTask` that only stores the object and the return value, not sure if it makes sense? If it does, should we try to make it public and use it in other places like here? [content_provider.rs#L391-L395](https://github.com/gtk-rs/gtk4-rs/blob/master/gdk4/src/subclass/content_provider.rs#L391-L395)
=> gio: add AsyncInitable subclassing support

gio/Gir.toml, gio/src/application.rs, gio/src/auto/application.rs, gio/src/lib.rs
These would automatically release/unmark_busy the application once
they're dropped and ensure that the release/unmark_busy operation is
called exactly the number of times the hold/mark_busy operation was
called.
=> gio: Use guard objects for `Application::hold()` and `mark_busy()`

.github/workflows/CI.yml
That last one wasn't right: https://github.com/gtk-rs/gtk-rs-core/actions/runs/2340331679/workflow#L37
It seems like a bad actions yaml should cause the build to fail instead of silent skipping that workflow...
=> Revert "ci: use set-safe-directory for gtk-rs/checker checkout"

gio/Gir.toml, gio/src/auto/socket_address_enumerator.rs
The `next` method (both the sync and async variants) relies on the
pointer being NULL to indicate the end of the address stream.
See also the corresponding MR to add the annotation in the glib source
code:
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2701
=> SocketAddressEnumerator: `next` return value should be nullable

glib/src/boxed.rs, glib/src/boxed_inline.rs, glib/src/object.rs, glib/src/shared.rs, glib/src/translate.rs
When transferring ownership of the container to the caller, the
container should be freed also when it is empty, since it might contain
a terminating NULL element. Calling g_free on a NULL container is
harmless, since in this case g_free is a no-op.
=> translate.rs: free the container memory also when the container is empty

gio/Gir.toml, gio/src/auto/subprocess_launcher.rs, gio/sys/Gir.toml, gio/sys/src/lib.rs
According to the gio public header, `g_subprocess_launcher_close` should
be available on unix platforms only:
https://gitlab.gnome.org/GNOME/glib/-/blob/glib-2-72/gio/gsubprocesslauncher.h#L81-115
=> ProcessLauncher: `close` method should be available on unix only

glib/src/gstring.rs
I'm running a lot of crates under AddressSanitizer. You can find these bugs in the `glib` crate by running this in it:
```
RUSTDOCFLAGS=-Zsanitizer=address RUSTFLAGS=-Zsanitizer=address cargo +nightly test -Zbuild-std --target=x86_64-unknown-linux-gnu
```
You should see an error that looks something like this
```
==324602==ERROR: AddressSanitizer: global-buffer-overflow on address 0x557a09bb8769 at pc 0x557a08a066b7 bp 0x7f845cfd7cf0 sp 0x7f845cfd74c0
READ of size 10 at 0x557a09bb8769 thread T37 (gstring::tests:)
#0 0x557a08a066b6 in __asan_memcpy /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:22:3
#1 0x557a08d66236 in core::intrinsics::copy_nonoverlapping::hca817e807f3b91c2 /home/ben/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src …
```
=> Fix off-by-one in GString::from (and missing null terminator in a test)

glib/src/param_spec.rs
The string is an interned string that is valid for the remaining runtime
of the process and is not bound by the `&self` reference.
----
See https://github.com/gtk-rs/gtk-rs-core/pull/726/files#r917705349
=> glib: Fix `ParamSpec::name()` return value lifetime

glib/src/gobject/signal_group.rs, glib/src/subclass/object.rs, glib/src/subclass/signal.rs
The return_type & param_types are optional, no need to enforce those
=> glib: Simplify SignalBuilder constructor

pango/src/glyph_info.rs
I believe this method should exist, so that after shaping, you can change, not only the position of glyphs, but which glyphs get chosen from shaping.
For example, shaping decides that tabs characters are displayed as arrows, and I would like to modify the glyph afterwards to be a space.  Or, maybe I want to display whitespace as visible.  In C, you would just modify the glyph field after shaping.  You should be able to modify it in rust too.
=> add set_glyph to GlyphInfo

gio/Gir.toml, gio/src/action_entry.rs, gio/src/action_map.rs, gio/src/auto/action_map.rs, gio/src/lib.rs, gio/src/prelude.rs
It is pretty useful for ActionMap implementors like GtkApplication
and GtkWindow. It avoids usually the usage of the clone! macro
as we pass the ActionMap to the activate/change_state callbacks.
Especially that Gtk doesn't provide a
gtk_application_class_install_action
alternative to the gtk_widget_class_install_action.
=> gio: Manually implement ActionEntry

glib/src/subclass/shared.rs, glib/src/subclass/types.rs
Nothing unsafe about getting a pointer, deferencing it is unsafe.
=> as_ptr() and as_mut_ptr() accessors are safe

glib/src/object.rs
This helps user localize panics resulting from their code.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: BoolError { message: "property 'max-buffers' of type
[...]
**/home/francois/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/4ca23ca/glib/src/object.rs:2372:53**
thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: BoolError { message: "property 'max-buffers' of type
[...]
**generic/threadshare/examples/standalone/main.rs:148:18**
=> glib/object: add track_caller annotation in a few places

glib/Cargo.toml, glib/src/subclass/types.rs
While profiling the standalone threadshare benchmark in
gst-plugins-rs, callgrind showed 2% cycles spent in
`ElementImplExt::panicked`. This function retrieves the
panicking status in trampolines and makes use of
`instance_data` from `ObjectSubclass`, which is stored in
a `HashMap`.
Rust's `std::collections::HashMap` is known to make use of
a ["hashing algorithm selected to provide resistance against
HashDoS attacks"](https://doc.rust-lang.org/std/collections/struct.HashMap.html). Since the `intance_data` is indexed
by a `glib::Type`, I thought it would make sense to test a
less strict but quicker hasher.
I first tested [`fnv`](https://crates.io/crates/fnv) which is an implementation of the
Fowler-Noll-Vo hash function which is used in major crates
such as `hashbrown`. The crate …
=> glib/types: use rustc-hash for HashMap

.github/workflows/CI.yml, .github/workflows/docs.yml, .gitmodules, README.md
This makes sure that cargo does not clone and checkout all the
submodules if pointing to this repository as a git dependency.
To checkout the submodules `git submodule update --checkout` can be
used.
=> Don't checkout submodules by default

glib/Cargo.toml, glib/src/subclass/types.rs
According to callgrind, using `ts-standalone` with `-s 1000 -n 1000`, there's a 17% reduction in estimated cycles for
`ElementImplExt::panicked` (invoked more than 1M times) compared to current version which uses `HashMap` with `rustc_hash`.
`ElementImplExt::panicked` makes use of `instance_data` from `ObjectSubclass`.
See also: https://github.com/gtk-rs/gtk-rs-core/pull/755
=> glib/subclass/types: use BTreeMap instead of HashMap

glib/src/object.rs
The [`Borrow`](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) trait is more restrictive than
`AsRef`, but since `PartialOrd`, `Hash`, `PartialEq`, (...), are all implemented on the object pointer,
it's safe, and I believe correct, to implement `Borrow`.
Closes #711. Covers my use case in the Properties macro
=> Implement Borrow on object types

cairo/src/context.rs, cairo/src/device.rs, cairo/src/patterns.rs, cairo/src/pdf.rs, cairo/src/surface.rs, cairo/src/surface_macros.rs, glib/src/param_spec.rs
Instead of requiring the user to go through the Deref implementation
Fixes #189
=> cairo: Use AsRef<T> for custom subclassing types

cairo/src/stream.rs, glib-macros/tests/test.rs
When running `cargo doc --all-features`, I got two warnings (and a lot of deprecation warnings, which I ignored).
1. A doc link was broken (rustdoc::broken_intra_doc_links)
2. A needless borrow
=> Fixed clippy lints and warnings

glib/src/object.rs
Doesn't cost us anything and I can make use of it in GStreamer for an extension trait
=> glib: Add a getter for `ObjectBuilder::type_`

glib-macros/src/lib.rs
These were moved to `subclass::basic` in 6a19f8de4332df36893c7c901a6dd26064c08881.
=> Correct outdated references to `subclass::simple`

glib/src/subclass/types.rs
For the lazy among us and it also mirrors `imp()` more closely, which is not called `implementation()` either.
----
CC @A6GibKm
=> glib: Add `ObjectSubclass::obj()` as a shorter alias for `instance()`

gio/src/settings.rs
As the default value is GET|SET
=> gio: Add set_only/get_only helpers to BindingBuilder

.github/workflows/image.yml
Rebuild the gtk-rs-core image once every week. The current image is already 5 months old and I suspect this to be the reason why the relm4 docs pipeline [fails](https://github.com/Relm4/docs/actions/runs/3322872513/jobs/5492499363#step:3:331) with some weird permission errors while building libpanel (but I might be wrong). 
Anyway, there's no good reason to pull the image from Fedora rawhide and then let it age for several weeks, right?
I think weekly builds are reasonable and if desired, I will send a PR for the gtk-rs image as well.
Btw. is there any reason why all the shell commands are connected with `&& \` in one single docker instruction?
=> image: Rebuild once every week

gio/Gir.toml, gio/src/auto/cancellable.rs, gio/src/cancellable.rs, gio/src/subclass/async_initable.rs
Regression from this change:
https://github.com/gtk-rs/gtk-rs-core/commit/7c9b36c270a945012a2f5d07c8d0f11912d66d34#diff-8439ea6875c9b60b7d07a7b39f6dde1d31d38459f7c27173e56b4cecb0eadefaR142
Basically `g_cancellable_set_error_if_cancelled()` doesn't follow the GError conventions - it's the inverse, it returns `TRUE` if an error was set, and `FALSE` otherwise.
We need to move this to manual implementation.
I caught this while updating ostree-rs-ext to use gio 0.15, and our https://github.com/ostreedev/ostree-rs-ext/blob/main/lib/src/tokio_util.rs unit test started to panic.
=> Move `g_cancellable_set_error_if_cancelled()` to manual

pango/Gir.toml, pango/src/auto/language.rs, pango/src/language.rs
It only ever returns `NULL` if passing `NULL`, which makes not much sense.
=> pango: Make `pango::Language::from_string()` infallible

glib/src/boxed.rs, glib/src/shared.rs
In some of my projects we use `#![deny(missing_docs)]`, and this trips up on these new generated `as_ptr` functions.
Document them on general principle.
=> glib: Add a doc string for `as_ptr` generated impls

glib/src/subclass/types.rs
Not causing any issues now, but `ptr::addr_of` has been stable for a while so we can get rid of the UB to avoid any future problems.
=> glib: fix undefined behavior in types::register_type

.github/workflows/windows.yml
I figured this should be updated along with https://github.com/gtk-rs/gtk3-rs/pull/793 before I forget. Also update the windows VM so we can get the latest version of python and gvsbuild, and update gvsbuild command as it now works like a real python package.
=> update windows CI to glib 2.74

glib/src/lib.rs, glib/src/object.rs, glib/src/prelude.rs
=> Add CastNone trait

glib/src/error.rs, glib/src/lib.rs, glib/src/log.rs, glib/tests/structured_log.rs
=> glib: Use actual function name in `glib::BoolError` and include function name/source file/line number in structured logs

glib/Gir.toml, glib/src/auto/enums.rs, glib/src/auto/mod.rs, glib/src/convert.rs, glib/src/gstring.rs
I decided to make most of these associated functions on `GStr`, except for the utf8<->utf32 conversions.
Ref #763
=> glib: Bind more `g_utf8` APIs

gio/src/task.rs, glib/src/lib.rs, glib/src/main_context_futures.rs, glib/src/source.rs, glib/src/thread_pool.rs
Fixes #792
After looking at the equivalent tokio API I noticed we don't install unwind handlers, maybe that is something that should happen?
=> gio: add spawn_blocking()

.github/workflows/CI.yml, glib/Cargo.toml, glib/src/convert.rs, glib/src/functions.rs, glib/src/gstring.rs, glib/src/gstring_builder.rs, glib/src/lib.rs, glib/src/translate.rs, glib/src/utils.rs
Update: See comment https://github.com/gtk-rs/gtk-rs-core/pull/600#issuecomment-1302872708 for the general status of this PR. 
Original comment: All of these `TryFrom` are panicking when they don't really need to. This is probably going to break some other things, I'd like to check this against gtk-rs and gstreamer-rs at least. Another option is to leave the panicking `From` traits in and also support `TryFrom`.
Also makes `GString` deref as a `GStr`
=> GString refactor

glib-macros/src/error_domain_derive.rs, glib-macros/src/lib.rs
Since the quark string is part of the public API (it ends up in the gir file), follow the same convention used by glib.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/873
=> Suggest kebab-case for the error domain

glib/src/collections/list.rs, glib/src/collections/slist.rs
It's not necessary to free them or to explicitly copy them.
=> glib: Minor optimization for `List`/`SList` with `Copy` types

glib/src/boxed.rs, glib/src/boxed_inline.rs, glib/src/object.rs, glib/src/shared.rs, glib/src/subclass/signal.rs, glib/src/translate.rs, glib/src/types.rs
Use memcpys if possible instead of manual loops, and directly write into
the `Vec` memory and set the length afterwards to avoid having the
reallocate logic at every step.
=> glib: Optimize various from/to `Vec` FFI translation functions

glib/src/object.rs, glib/src/quark.rs, glib/src/subclass/signal.rs, glib/src/types.rs
This reduces allocations as all those strings are usually small and would be stack-allocated now for adding the NUL-terminator.
=> glib: Use `IntoGStr` trait in a couple of places

README.md, cairo/Cargo.toml, cairo/README.md, cairo/sys/Cargo.toml, examples/Cargo.toml, gdk-pixbuf/Cargo.toml, gdk-pixbuf/README.md, gdk-pixbuf/sys/Cargo.toml, gio/Cargo.toml, gio/README.md, gio/sys/Cargo.toml, glib-build-tools/Cargo.toml, glib-build-tools/README.md, glib-macros/Cargo.toml, glib/README.md, glib/gobject-sys/Cargo.toml, glib/sys/Cargo.toml, graphene/Cargo.toml, graphene/README.md, graphene/sys/Cargo.toml, pango/Cargo.toml, pango/README.md, pango/sys/Cargo.toml, pangocairo/Cargo.toml, pangocairo/README.md, pangocairo/sys/Cargo.toml, tests/two-levels-glib-dependent/glib-dependent-dependent/Cargo.toml, tests/two-levels-glib-dependent/gstreamer/Cargo.toml, tests/two-levels-glib-dependent/gtk/Cargo.toml
Commit a577a12b761654a752564d427e824bb409e3c13d bumped it for glib. Update the README accordingly and also set the MSRV for other crates since most of them depend on glib and because this way we are consistent.
=> Bump MSRV to 1.64 everywhere

pango/src/functions.rs
As discussed in chat, we could also change the signature to take `&[Item]` and avoid the cloning, but I am not familiar enough with the use of this API to understand if that would be problematic for the caller
=> pango: use the new List api to simplify reorder_items

glib-build-tools/src/lib.rs
According to [this report](https://github.com/rust-lang/rust/issues/75075) "/" as a path separator may not work on Windows.
Related: https://github.com/gtk-rs/gtk-rs-core/blob/master/gio/src/resource.rs#L53
=> Do not hard-code path separator

glib-build-tools/src/lib.rs
I have to admit that I don't fully understand why this is happening, but if glib-compile-resources fails due to a bad file for example, the current code ends up printing no error message at all.
It seems that the stderr from the failing command and the stderr of the assert somehow cancel each other out.
With this patch, the stderr of the command is properly recorded and explicitly written to the stderr of the build script through the assert. This fixed the error reporting in my case and should be a much more robust solution in general.
=> build-tools: Fix reporting of errors

examples/gio_task/file_size/mod.rs, gio/src/async_initable.rs, gio/src/initable.rs, gio/src/read_input_stream.rs, gio/src/subclass/initable.rs, gio/src/task.rs, gio/src/write_output_stream.rs, glib/src/boxed_any_object.rs, glib/src/gobject/binding.rs, glib/src/gobject/binding_group.rs, glib/src/object.rs, glib/src/subclass/mod.rs, glib/src/subclass/object.rs, glib/tests/subclass_compiletest/01-auto-send-sync.rs, glib/tests/subclass_compiletest/02-no-auto-send-sync.rs, glib/tests/subclass_compiletest/04-auto-send-sync-with-send-sync-parent.rs, glib/tests/subclass_compiletest/05-no-auto-send-sync-with-non-send-sync-parent.rs, glib/tests/subclass_compiletest/06-no-auto-send-sync-with-non-send-sync-ffi-parent.rs
Nicer than writing `Object::new(&[])`.
Also optimize the object builder a bit.
=> glib: Add new object constructor for constructing an object with default property values

examples/build.rs, glib-build-tools/src/lib.rs
You can pass the command line tool multiple source dirs, so we should allow it too.
---
If this gets merged, I'll send corresponding PRs to the gtk4-rs/gtk3-rs repositories too
=> build-tools: Allow passing multiple source dirs to `compile_resources`

glib/src/gstring.rs
Deriving the impls would consider the trailing NUL-terminator but this is inconsistent with the other trait impls that don't consider it.
Also the `Debug` impl is now just printing the string.
=> glib: Implement various traits on `GStr` manually

gio/src/application.rs, gio/src/subclass/application.rs, glib/src/exit_code.rs, glib/src/lib.rs
Allows writing
```rust
fn main() -> ExitCode {
let app = gio::Application::new(None, Default::default());
// ...
app.run()
}
```
in Rust 1.61 or newer. 
Note that the [termination](https://doc.rust-lang.org/std/process/trait.Termination.html) trait is supported for any Result<T: Termination, E: Debug>, we might want to return that instead, but it is kinda redundant at gtk already returns errors as a number.
=> application: Return ExitCode

glib/src/collections/mod.rs, glib/src/collections/strv.rs, glib/src/gstring.rs, glib/src/lib.rs
It is useful to have also in cases different from StrV, for instance for some API we want to return a Slice of GStrPtr.
=> Rename StrVItem to GStrPtr and make it clonable and transparent

glib-macros/src/lib.rs
Related to the issue #932.
I'm not sure if types created with `glib::Enum` can be `nullable`...
=> Add doc for ConstructCell, improve doc Boxed, Enum

glib-macros/src/lib.rs
- have both the nullable and the not nullable case in the examples, otherwise user may assume that nullable is needed
- Replace 'eventually' with 'optionally'
- Align the SharedBoxed documentation
=> macros: further tweak docs

glib-macros/src/lib.rs, glib-macros/src/properties.rs, glib-macros/tests/properties.rs
The error messages are even better now, because the user will get `method x not defined on ParamSpecXBuilder` instead of a `Invalid attribute for property`.
Quite happy with the result :)
=> properties: Update syntax for custom flags and other builder fields

glib-macros/src/properties.rs, glib-macros/tests/properties.rs
=> properties: correctly type check value returned by the getter fn

glib/src/gstring.rs
Benchmarks show this to be a bit faster because `to_str` causes the string to be iterated twice.
Also add `GStr::from_ptr_checked` to ease with doing a utf8 check from a C pointer.
=> Use strcmp for GStringPtr comparisons

glib-macros/src/clone.rs, glib-macros/tests/clone.rs
Fixes #956.
What is it this PR doing? Instead of using `panic!` whenever we encounter an invalid input, it generates a `compile_error!` call with the span of the token which created the issue to trick the compiler into given the location we want.
Unfortunately, the spans are limited with stable rustc so I can't use `Span::join` to make it look better in some cases, but I think it remains a great improvement nonetheless.
=> Greatly improve `clone!` proc macro error output

glib-macros/tests/properties.rs, glib/src/property.rs
Before it wasn't possible to create a property without a wrapper like `RefCell` or `Mutex`
=> impl PropertyGet for T: `HasParamSpec`

glib/src/param_spec.rs
Make the API more symetric and may be useful if builder has been created with builder().
=> param_spec: add ParamSpecEnumBuilder::default_value()

glib/src/collections/strv.rs
And don't copy any strings in the ones for containers of already `NUL`-terminated strings.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/976
=> glib: Add various `IntoStrV` impls

graphene/src/box_.rs, graphene/src/matrix.rs, graphene/src/point.rs, graphene/src/point3_d.rs, graphene/src/rect.rs, graphene/src/vec2.rs, graphene/src/vec3.rs, graphene/src/vec4.rs
I made a gtk widget that uses graphene::Vec3 internally, 
https://github.com/yuraiz/telegrand/blob/animated-background/src/session/content/gradient_bg.rs
and because vectors doesn't implement Default I can't derive Default for widget implementation 
also it would be useful to have gdk::RGBA to vector conversions but that's compicated because those libraries are independent
=> Implement Default trait for vectors

glib-macros/tests/properties.rs, glib/src/property.rs
There's still some things to do, but I'm not sure how to do them:
1. How should I test these?
2. I'm not sure how to implement `PropertySetNested` for them
Closes #980
=> Make `WeakRef` and `SendWeakRef` useable with the `Properties` derive macro

glib-macros/src/properties.rs
Without this I am getting warnings about unused `connect_blah_notify` @ranfdev
=> glib-macros: allow properties macro generated functions to be unused

glib/src/object.rs
Does it make sense?
Related to #39
=> Implement PartialEq for WeakRef

gio/Gir.toml, gio/src/action_map.rs, gio/src/auto/simple_action.rs
This reverts commit 42c72aa9bfd40016e5b497c50950df19325b2f55.
The generated bindings are leaking the state parameter
=> Revert "SimpleAction: take state by value"

gio/src/list_store.rs
Instead construct a fake item here that satisfies the checks from GIO.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/997
=> gio: Don't pass `NULL` to `g_list_store_find_with_equal_func_full()`

glib-macros/tests/test.rs, glib/src/object.rs
Allows using `@watch` on `imp.obj()`.
cc @YaLTeR
=> glib: implement WatchedObject for BorrowedObject

glib-macros/tests/properties.rs, glib/src/param_spec.rs
=> impl HasParamSpec on glib::Variant

glib/src/collections/strv.rs
Calling `self.ptr.as_ptr` does not properly convert a 0-sized strv to a NULL-terminated array
=> strv: when calling g_strv ffi method, use our `as_ptr` implementation

glib/src/gobject/signal_group.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1021.
Didn't have a chance to test it locally because I couldn't use cargo patch in my project :/
=> glib: Add connect_notify* methods to SignalGroup

pangocairo/sys/Cargo.toml
It appears that this was overwritten by accident at some point.
=> pangocairo-sys: fix package.description in Cargo.toml

glib-macros/src/lib.rs, glib-macros/src/properties.rs, glib-macros/tests/properties.rs
Fixes #990
I know, if a `ParamSpecBuilder` has a method `nullable`, this attribute will now shadow it. But I don't know any ParamSpec with a method named `nullable`. And even if that exists, the builder pattern can always be used: `builder().nullable()`.
This change is backwards compatible (expect if someone is using a builder with a `nullable` method I guess...).
Any other solution doesn't seem to be more backward compatible than this.
Also, the `nullable` attribute is used already by other macros, such as `glib::Boxed`, so this behavior seems consistent to me. 
If this isn't enough, we will introduce something better, introducing breaking changes, for the next milestone.
=> Add nullable attribute on properties macro

glib/Cargo.toml, glib/benches/gstring.rs, glib/src/gstring.rs
And add a bench too, for me it shows this is faster for the small string case.
=> glib: Only optimize `IntoGStr` for `String` when capacity allows

gio/src/subclass/mod.rs, gio/src/subclass/socket_control_message.rs
Adds the possibility to subclass [`gio::SocketControlMessage`](https://gtk-rs.org/gtk-rs-core/git/docs/gio/struct.SocketControlMessage.html) to be subclassed to implement new messages.
=> Added subclassing support for gio::SocketControlMessage

gio/src/socket.rs, glib/src/translate.rs
Fixes unit tests under macOS and possibly some other *nix flavors :
- Optional use of `SOCK_CLOEXEC` on platforms that do not support the flag
- Fixed `Path` constructor usage in macOS tests
About the `SOCK_CLOEXEC` option: I did a deep dive into libc codebase to find what are the supported platforms and I think I came with an exhaustive list (that includes enscriptem... I'm skeptical about that one, but libc defines the flag, so I did put it in). That said, I don't think there's a real need for the unit test to use `SOCK_CLOEXEC` (but I'm not the author of the test, so who knows), so another option is to just remove the flag for all platforms to reduce the clutter in the code.
=> Fixed unit tests under macOS and possibly other *nix flavors

glib/src/gstring.rs
Another zero copy optimization. With the collection return types, some methods can `List<GStringPtr>` so this lets you get a string out of them and cheaply convert it
=> glib: implement From<GStringPtr> for GString

glib-macros/src/properties.rs
TryFrom is in scope only on rust=2021 or newer
=> glib-macros: Don't assume edition=2021

glib-macros/src/lib.rs, glib-macros/src/value_delegate_derive.rs, glib-macros/tests/value_delegate_derive.rs
This allows `Ident` (not only `&Ident`) to be allowed on functions that take in `Into<Value>`.
=> glib-macros: generate "From<Ident> for Value" on ValueDelegate

glib/src/property.rs
I have been building gst-plugins-rs 0.9 for a while for a mips32 chip, but when bumping to 0.10 I got issues compiling due to that chip not supporting 64-bit atomics. The following patch fixes compilation on that target.
=> glib: Fix building for architectures without 64-bit atomics

glib/src/win32.rs, glib/sys/Gir.toml, glib/sys/src/manual.rs
In an attempt to solve #2, I have tried to write wrappers for the `g_win32_*` functions.
All of the functions listed on the issue have been implemented manually.
=> Implement bindings for g_win32 functions

glib-macros/Cargo.toml
The code in this crate uses features of "syn" which are only present
when the default features are enabled. This previously worked "by
accident" because other crates in the dependency tree pulled in the
"default" feature of syn, but these crates have started moving to
syn v2, so this is no longer the case.
=> glib-macros: enable default features of syn

glib-macros/src/boxed_derive.rs, glib-macros/src/downgrade_derive/enums.rs, glib-macros/src/downgrade_derive/structs.rs, glib-macros/src/enum_derive.rs, glib-macros/src/error_domain_derive.rs, glib-macros/src/flags_attribute.rs, glib-macros/src/properties.rs, glib-macros/src/shared_boxed_derive.rs, glib-macros/src/utils.rs, glib-macros/src/value_delegate_derive.rs, glib-macros/src/variant_derive.rs
Having a custom eg. result type in scope will fail compilation, as the types don't match. Specify quoted types explicitly to not rely on the prelude.
=> glib-macros: Specify quoted types explicitly

glib/src/param_spec.rs, glib/src/types.rs, glib/src/value.rs
There's no separate GType for that unfortunately and it's up to the caller to select whether this is an actual `String` or a `Path`. If getting this wrong it will fail the same way it would now already fail for strings.
=> glib: Allow using `Path` / `PathBuf` in `glib::Value`s

glib-macros/src/properties.rs
If merged, structs deriving `glib::Properties` should now be able to compile without having `glib::ParamSpecBuilderExt` exist in the module scope where the struct is declared.
=> glib-macros: Import ParamSpecBuilderExt	inside the scope of DerivedObjectProperties::derived_properties

glib-macros/src/properties.rs
If merged, structs with a property named "error" will be able to compile successfully.
Fixes #1067
=> glib-macros: Disambiguate TryFrom<usize>::Error for DerivedPropertiesEnum

glib-macros/src/properties.rs
If merged, structs with members named `r#fn`, `r#loop`, `r#pub`, etc. will be able to derive `glib::Properties`.
=> glib-macros: Strip raw identifier prefix from struct members for the Properties macro

glib-macros/src/lib.rs, glib-macros/src/properties.rs, glib-macros/tests/properties.rs
If merged, the `r#` prefix will be removed from names of the property, allowing the expected names to be used.
This also adds a section to the `glib::Properties` docs elaborating the use of keywords as property names with the macro.
=> glib-macros: Strip out r# prefix from property names inside the GObject

glib/Cargo.toml
This all require a newer rustc than what smallvec depends on, but much older than glib's minimum supported Rust version.
Enabling these features enables smallvec to use less space, work with any array size and provide some more const functions.
----
Another reason why conservative MSRV are the plague.
=> glib: Enable various smallvec features

pango/sys/Cargo.toml
=> pango: Lower pkg-config version requirement for v1_52

.github/workflows/docs.yml, cairo/Cargo.toml, cairo/src/lib.rs, gdk-pixbuf/Cargo.toml, gdk-pixbuf/sys/Cargo.toml, gio/Cargo.toml, gio/sys/Cargo.toml, glib/Cargo.toml, glib/gobject-sys/Cargo.toml, glib/sys/Cargo.toml, graphene/Cargo.toml, graphene/sys/Cargo.toml, pango/Cargo.toml, pango/sys/Cargo.toml, pangocairo/Cargo.toml, pangocairo/sys/Cargo.toml
Fix for https://github.com/gtk-rs/gtk-rs-core/issues/1090 on the gtk-rs-core side
It seems like you need both RUSTFLAGS and RUSTDOCFLAGS because `build.rs` doesn't care about the doc flags and cargo only passes RUSTDOCFLAGS to rustdoc...
=> Fix required features not shown in docs

glib-macros/src/lib.rs, glib-macros/src/properties.rs, glib-macros/tests/properties.rs
This allows to omit `set` for `construct_only` properties, as it is confusing from a semantic perspective, because we don't actually generate a public setter. It was required before, but didn't actually throw an error but panic at runtime.
Updates the docs about how to use `construct_only` and chooses a better example for the `builder()` attribute.
Closes #1088
=> properties: Allow to omit set for construct_only properties

glib-macros/Cargo.toml, glib-macros/src/boxed_derive.rs, glib-macros/src/enum_derive.rs, glib-macros/src/error_domain_derive.rs, glib-macros/src/flags_attribute.rs, glib-macros/src/lib.rs, glib-macros/src/object_subclass_attribute.rs, glib-macros/src/properties.rs, glib-macros/src/shared_boxed_derive.rs, glib-macros/src/utils.rs, glib-macros/src/value_delegate_derive.rs, glib-macros/src/variant_derive.rs
closes #1061 
**Problem**
syn 2.0 removed the type `NestedMeta`, that was extensively used by gtk-rs-core to parse macro attributes, without providing a direct replacement type.
Instead, the suggested way to parse an attribute is now to use [`Attribute::parse_nested_meta`](https://docs.rs/syn/latest/syn/struct.Attribute.html#method.parse_nested_meta), which iterates over the arguments of an attribute and forces you to parse them. `parse_nested_meta` tracks the spans of the arguments being parsed, so in the case an error is returned, it provides good error messages.
Most of the glib-macros depended on utility functions defined in `glib-macros::utils`. Those functions often tried to retrieve a single argument inside an attribute, without caring about the other arguments. This is not …
=> Update syn: v2.0

glib/src/collections/strv.rs
Found by running tests with AddresSanitizer: https://asan.saethlin.dev/ub?crate=glib&version=0.17.9
I don't think this qualifies as a security issue, every malloc implementation should actually allocate the intended amount of memory anyway.
=> Fix heap buffer overflow due to operator precedence

glib/src/collections/strv.rs
This was implemented for GString and &str but not for &GStr.
=> strv: Implement From for constant GStr slices

glib/src/subclass/types.rs
Doing this violates Rust's [strict provenance rules][1]. Unfortunately, the API for doing this properly ([`ptr::expose_addr`][2]) isn't ready yet. However, we can work around this on stable Rust by casting through `isize` for offset calculations.
[1]: https://doc.rust-lang.org/std/ptr/index.html
[2]: https://doc.rust-lang.org/std/primitive.pointer.html#method.expose_addr
=> glib: Do not use ptr::offset/offset_from for private/impl offset

glib/Cargo.toml, glib/src/property.rs
That adds std::cell::OnceCell and std::sync::OnceLock support for the properties macro.
=> Add a std_once_cell feature 

gio/src/datagram_based.rs, gio/src/pollable_input_stream.rs, gio/src/pollable_output_stream.rs, gio/src/socket.rs, glib/src/main_context_channel.rs, glib/src/prelude.rs, glib/src/source.rs, glib/src/source_futures.rs
=> glib: Replace Continue with ControlFlow

gio/src/list_store.rs
Motivation:
People often endup doing
```rust
for item in list_store.iter()
if item.unwrap().name() == 'Giorgio' {
list_store.remove(&item)
}
}
```
But that `unwrap` is going to panic, because we added checks to prevent that an iterator over a list is mutated during iteration.
`retain` is just a nice alternative to provide an easier to use way to remove items while iterating the list.
```rust
list_store.retain(|item| item.name() != 'Giorgio')
```
It will also remove consecutive items with a single `splice` call, so If the user removes every item, `retain` doesn't spam `items_changed` signals
=> Add retain method to ListStore

glib/src/gobject/flags.rs
Fixes https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/issues/475
I ran generator.py but nothing has changed.
=> fixed missing 512 flag, renamed 256 to USER_0

glib/src/param_spec.rs, glib/src/types.rs, glib/src/value.rs
=> Add support for NonZeroT types

glib-macros/Cargo.toml, glib-macros/src/clone.rs, glib-macros/tests/clone.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1102.
=> Don't generate unit tuple in clone macro as default-return value

gio/src/input_stream.rs
=> Fix panic in gio InputStream

glib-macros/src/lib.rs
There was a typo and I think a clear example doesn't hurt either.
=> Fix docs of `glib::derived_properties`

gio/Gir.toml, gio/src/auto/file_info.rs
Following the annotations from upstream https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gfileinfo.c#L1349 & https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gfileinfo.c#L981
=> gio: Set missing annotations for new FileInfo apis

.github/workflows/typos.yml, .typos.toml, examples/gio_task/main.rs, gio/Gir.toml, glib-macros/src/downgrade_derive/fields.rs, glib-macros/src/lib.rs, glib-macros/src/properties.rs, glib/Gir.toml, glib/src/gobject/binding_group.rs, glib/src/log.rs, glib/src/object.rs, glib/src/property.rs, glib/src/subclass/object.rs, glib/src/value.rs, pango/src/enums.rs
=> Add typos workflow

cairo/src/pdf.rs, cairo/src/svg.rs, gio/src/lib.rs, gio/src/socket.rs, gio/src/subprocess_launcher.rs, gio/src/unix_mount_point.rs, glib/src/source.rs, glib/src/source_futures.rs
Remaining cleanup from https://github.com/gtk-rs/gtk-rs-core/pull/1078
=> Disentangle docsrs and features

glib-macros/src/lib.rs, glib-macros/src/properties.rs, glib-macros/tests/properties.rs
closes #1059. Currently the user must always specify the name of the ext_trait.
Note: the ext trait is inevitably defined in the same `imp` module where `#[derive(Properties)]` is called. 
Sadly this feature won't support adding other methods generated by a signal macro, because macros can't share data and the entire trait definition must happen in one macro.
=> Add support for ext_trait in properties macro

glib/src/boxed.rs, glib/src/shared.rs
It makes it clearer that an `XMemoryManager` only manages a single target type.
=> Use associated type in memory managers

.typos.toml, glib/Gir.toml, glib/src/auto/enums.rs, glib/src/auto/mod.rs, glib/src/lib.rs, glib/src/unichar.rs
I'm not sure if documentation for these methods can be automatically generated given these are manually defined as methods on an extension trait.
I *think* I got all of the ones not offered by the stdlib
Closes #763 
---
Some notes:
* names were made "rustier", e.g.:` g_unichar_istitle` became `is_titlecase`
* I did not include APIs that were already availabe through Rust's char
=> glib: Bind `g_unichar` APIs

glib/src/lib.rs
The blogpost[1] mentions that these are re-exported, so to avoid causing confusion, make it so these appear in documentation.
[1]: https://gtk-rs.org/blog/2023/08/28/new-release.html#switch-to-bitflags-20
---
Alternatives:
- do nothing
- remove the note about the two crates being re-exported from the blogpost
=> glib: Remove `#[doc(hidden)]` from `once_cell` and `bitflags` re-export

glib-macros/src/lib.rs
I copied the example in a playground to understand why my properties are not working in the project I'm working on, and found out those two imports can be removed.
=> glib-macros: Remove unused imports from Properties doc test

glib-macros/src/properties.rs
This PR should fix #1186 
I'm still not convinced that `quote_spanned` is correctly used (because there are obviously a lot of tokens which have nothing to do with the span of the attribute), but I don't know the reasoning behind the code, so adding `#[must_use]` to the codegen is the easiest fix and actually a useful addition even if you don't use `clippy::must_use_candidate`.
=> glib-macros: Mark property getters as #[must_use]

pango/Gir.toml, pango/src/auto/glyph_string.rs
pango glyph_string's methods index_to_x and x_to_index use the analysis parameter, but don't modify it.  This changes the pango/Gir.toml to make the analysis parameter not be &mut.
=> fix glyph string analysis methods that don't need &mut

glib/src/collections/strv.rs, glib/src/gstring.rs
I was updating some code to glib 0.18 and we were previously using `as_str()` - which is what the default Rust nomenclature for an *infallible* reference-to-reference conversion uses.
The `to_str()` is used for fallible conversions
(e.g. https://doc.rust-lang.org/std/ffi/struct.OsStr.html#method.to_str) which this is not.
=> glib/GStringPtr: Add `as_str()` and `Deref<Target=&str>`

glib/src/error.rs
Not sure if this is the best way to go about it
Fixes #1209
=> glib: Allow variable expansion in format strings passed to bool_error & result_from_gboolean

gio/src/action_map.rs
Otherwise it is not possible to drop the ActionMap without dropping the actions first.
See https://github.com/gtk-rs/gtk4-rs/issues/1516.
=> gio: Use weak reference to ActionMap when adding action entries

glib-macros/src/properties.rs, glib-macros/tests/properties.rs
Without this, it's impossible to use the generated ext trait on a subclass.
When a property is overridden, the getter and setter is not generated, because that property should be accessed through the parent interface/trait. What do you think about that?
=> Implement ext trait on IsA<T>, don't generate overridden methods

glib/src/source.rs
Just copying and pasting with minimal changes.
Closes #1148
=> Add _full and _local_full methods for idle and timeout callbacks that take priority

examples/Cargo.toml, examples/object_subclass/author.rs, examples/object_subclass/main.rs
I'd like having a copy/pastable file to use when I need a simple gobject to store some data. I think many people would find this useful.
=> Add object_subclass example

glib-macros/src/lib.rs, glib-macros/src/object_interface_attribute.rs, glib-macros/src/object_subclass_attribute.rs, glib-macros/tests/dynamic_objects.rs, glib/Gir_GObject.toml, glib/src/gobject/auto/flags.rs, glib/src/gobject/auto/mod.rs, glib/src/gobject/dynamic_object.rs, glib/src/gobject/interface_info.rs, glib/src/gobject/mod.rs, glib/src/gobject/type_info.rs, glib/src/gobject/type_module.rs, glib/src/gobject/type_plugin.rs, glib/src/gobject/type_value_table.rs, glib/src/lib.rs, glib/src/prelude.rs, glib/src/subclass/interface.rs, glib/src/subclass/mod.rs, glib/src/subclass/type_module.rs, glib/src/subclass/type_plugin.rs, glib/src/subclass/types.rs, glib/src/types.rs
This PR aims to add support of module types and interfaces. See https://docs.gtk.org/gobject/class.TypeModule.html
The new macros `module_object_subclass` and `module_object_interface` allow to register types and interfaces that are part of a module (e.g. a shared library on linux). The macros mimic `object_subclass` and `object_interface` but generate code that support registration when the module (`TypeModule`) is loaded, following the behavior defined in Glib doc. However it is possible to postpone the registration at first use of the type (like for `object_subclass`) by explicitly setting the macro attribute `lazy_registration = true`.
Some examples in `glib-macros/tests/test.rs`, `glib/src/subclass/mod.rs` and `glib/src/subclass/type_module.rs`
=> add support of module types

gio/src/unix_socket_address.rs
as_os_str().len() does not return the number of bytes in the string, but the full allocation size. Just pass -1 and let glib calculate the len.
=> gio: fix UnixSocketAddress constructor with a path

Cargo.lock, cairo/src/win32_surface.rs, cairo/sys/Cargo.toml, cairo/sys/src/lib.rs, gio/sys/Cargo.toml, gio/sys/src/manual.rs
windows-sys / windows is also used by the gdk4-win32 crate.
=> Move from unmaintained winapi crate to windows-sys

glib/src/main_context_channel.rs
It was already removed in git master and giving an advance warning seems useful so people already port now if possible.
=> glib: Deprecate main context channel

gio/src/task.rs
This tells GIO that the task did in fact complete, and avoids a log message when the task is finalised
=> gio: return NULL from spawn_blocking's underlying gtask

glib-macros/src/boxed_derive.rs, glib-macros/src/shared_boxed_derive.rs
As far as I understand this is needed to make To/FromGlibContainer traits work
=> macros: generate GlibPtrDefault when deriving Boxed and SharedBoxed

glib-macros/src/enum_derive.rs, glib-macros/src/lib.rs, glib-macros/src/object_interface_attribute.rs, glib-macros/src/object_subclass_attribute.rs, glib-macros/tests/dynamic_enums.rs, glib-macros/tests/dynamic_objects.rs, glib/Gir_GObject.toml, glib/src/enums.rs, glib/src/gobject/dynamic_object.rs, glib/src/gobject/type_module.rs, glib/src/lib.rs, glib/src/subclass/mod.rs, glib/src/subclass/type_module.rs, glib/src/subclass/type_plugin.rs
This PR aims to add support of enums registered as dynamic types. See [https://docs.gtk.org/gobject/class.TypeModule.html](https://docs.gtk.org/gobject/class.TypeModule.html)  and [https://docs.gtk.org/gobject/iface.TypePlugin.html](https://docs.gtk.org/gobject/iface.TypePlugin.html).
The new macro `dynamic_enum_derive` allows to register enums that are part of a module or of a plugin (e.g. a shared library on linux). The macro mimic `enum_derive` but generates code that support registration when the plugin (`TypePlugin`) is used, following the behavior defined in Glib doc. However it is possible to postpone the registration at first use of the enum (like within `enum_derive`) by explicitly setting the macro attribute `lazy_registration = true`.
Some examples in …
=> Add support of enums as dynamic types

glib-macros/src/enum_derive.rs, glib-macros/src/lib.rs, glib-macros/src/object_interface_attribute.rs, glib-macros/src/object_subclass_attribute.rs, glib-macros/src/utils.rs, glib-macros/tests/enum_dynamic.rs, glib-macros/tests/object_subclass_dynamic.rs, glib/src/lib.rs, glib/src/subclass/interface.rs, glib/src/subclass/mod.rs, glib/src/subclass/type_module.rs, glib/src/subclass/type_plugin.rs, glib/src/subclass/types.rs
This PR aims to refactor the macros to register dynamic types, by replacing a macro by a macro helper attribute for `object_subclass`, `object_interface` and `Enum`
=> Refactor macros to register dynamic types

glib-macros/src/enum_derive.rs, glib-macros/src/object_interface_attribute.rs, glib-macros/src/object_subclass_attribute.rs
This PR aims to fix the concurrency issues in code generated by the macro helper attributes `object_subclass_dynamic` and `object_interface_dynamic`
=> Fix concurrency issues

glib-macros/src/enum_derive.rs, glib-macros/src/flags_attribute.rs, glib-macros/src/lib.rs, glib-macros/tests/flags_dynamic.rs, glib/Gir_GObject.toml, glib/src/enums.rs, glib/src/gobject/dynamic_object.rs, glib/src/gobject/type_module.rs, glib/src/subclass/type_plugin.rs
This PR aims to add support of flags registered as dynamic types. See https://docs.gtk.org/gobject/class.TypeModule.html and https://docs.gtk.org/gobject/iface.TypePlugin.html.
The new macro `flags_dynamic` allows to register the flags that are part of a module or of a plugin (e.g. a shared library on linux). This helper macro generates code that support registration when the plugin (`TypePlugin`) is used, following the behavior defined in Glib doc. However it is possible to postpone the registration at first use of the flags by explicitly setting the macro attribute `lazy_registration = true`.
=> add support of flags registered as dynamic types

cairo/sys/Cargo.toml
Hi,
This PR fixes a typo in the requested version of Cairo when the feature `v1_18` is enabled.
Without this patch, this error occurs:
```
Compiling rsvg_convert v2.57.91 (E:\librsvg\rsvg_convert)
error: linking with `link.exe` failed: exit code: 1120
|
= note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.39.33428\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" <snip> "windows.0.52.0.lib" "cairo-gobject.lib" "png16.lib" "z.lib" "gio-2.0.lib" "xml2.lib" "pangocairo-1.0.lib" "cairo.lib" "pangoft2-1.0.lib" "pango-1.0.lib" "gobject-2.0.lib" "glib-2.0.lib" "intl.lib" "harfbuzz.lib" "fontconfig.lib" "freetype.lib" "pangocairo-1.0.lib" "pango-1.0.lib" "gobject-2.0.lib" "glib-2.0.lib" "intl.lib" "harfbuzz.lib" "cairo.lib" "cairo-gobject.lib" "cairo.lib" …
```
=> cairo: Fix version of the v1_18 feature

Cargo.toml, cairo/Cargo.toml, cairo/sys/Cargo.toml, gdk-pixbuf/Cargo.toml, gio/Cargo.toml, glib/Cargo.toml, graphene/Cargo.toml, pango/Cargo.toml, pangocairo/Cargo.toml
The workspace one is not picked... no idea why & how
cc @sdroege
=> docs: Move metadata back to packages

glib/src/quark.rs
This avoids an allocation if the string is already statically allocated.
=> glib: Add `Quark::from_static_str()`

pango/src/attr_int.rs
Added BaselineShift, Sentence, TextTransform, and Word attributes.
=> pango: add some missing AttrInt constructors.

glib/src/main_context_futures.rs, glib/src/subclass/shared.rs
Otherwise it's going to be leaked if the future is dropped/aborted before it yields a value.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1326
=> glib: Drop the main context future return value sender on finalize

gio/src/subclass/application.rs
Correctly free items from `ArgumentList`.
Extend tests a bit.
Fix #1330
=> gio: correctly free argument list items

Cargo.lock, glib/src/collections/strv.rs
It will panic in debug builds when trying to access indices outside the slice. Instead, use pointer operations here to check that there is a `NULL` at the end of the array.
=> glib: Don't misuse `slice::get_unchecked()`

glib/src/variant_iter.rs
Passing an immutable reference (&p) to a function that mutates the data behind the pointer violates Rust's invariants.
This causes multiple tests in the test suite to crash when compiling it with optimizations (either `--release` mode or with `opt-level` of 2 or 3) with recent Rust versions, which is easy to reproduce, especially with nightly Rust:
```
$ cargo +nightly test --release --package glib
(...)
error: test failed, to rerun pass `--lib`
Caused by:
process didn't exit successfully: (...) (signal: 11, SIGSEGV: invalid memory reference)
```
Looks like this wasn't caught earlier because the wrapped C function is variadic and there's less type checking happening because of that.
=> glib: fix UB in VariantStrIter::impl_get

glib-macros/src/lib.rs
Mostly copy paste from the `construct_only`.
=> docs: `construct` attribute for `glib::Properties`

glib/sys/tests/manual.h
This pull request adds missing includes and fallback definitions in `manual.h` when performing unit tests on Unix platforms.
=> glib-sys: Add missing includes in `manual.h`

glib/sys/Gir.toml, glib/sys/src/lib.rs, glib/sys/tests/abi.rs, glib/sys/tests/layout.c
This pull request fixes the `GStaticMutex` and `GStaticRecMutex` size mismatches by removing them from the bindings.
See #1353 for more information.
=> glib-sys: fix struct size mismatches

glib-macros/src/properties.rs
=> glib-macros: Improve error message when `Properties` struct doesn't have at least one `#[property(…)]`

glib-macros/src/properties.rs, glib-macros/tests/properties.rs
As discussed in matrix. The rationale would be that this is useful for refactoring. We unfortunately can't emit custom warnings inside property macros. Otherwise I would prefer if the macro emitted a helpful warning.
Right now the macro emits one `unreachable expression` warning at the macro site if the enum is empty. Does this make sense to keep or should I silence it as well?
=> glib-macros/properties: Allow structs with no properties

glib/src/boxed.rs, glib/src/boxed_inline.rs, glib/src/object.rs, glib/src/shared.rs
Annotate the generated impls and types with doc comments. This makes it clear which types are copy-on-clone and which types are reference counted without looking at the source.
=> glib::wrapper: Add docs for impls generated by the wrapper macro

glib/src/win32.rs, glib/sys/src/manual.rs
These were temporarily auto-generated in 0.19 but then disappeared from the .gir file again. Re-add them with the auto-generated names, and add all missing ones.
=> glib: Re-add and rename manual Win32 API additions

glib/src/main_context_futures.rs
Other runtimes need to do this too https://docs.rs/async-std/latest/async_std/task/struct.JoinHandle.html#impl-Send
=> glib: Only implement Send on JoinHandle if the result is Send

glib/src/thread_guard.rs
Closes #1385. Wasn't sure whether there was some undocumented and esoteric reason this is unsafe to do. Seems fine to me and nobody has come forth in the issue to claim it would be unsafe.
=> glib: Implement Sync for ThreadGuard

glib-macros/tests/object_subclass_dynamic.rs, glib/src/object.rs, glib/src/subclass/interface.rs, glib/src/subclass/mod.rs, glib/src/subclass/object.rs, glib/src/subclass/types.rs, glib/src/wrapper.rs
This makes ObjectInterface and ObjectSubclass more similar to each other and allows for cleaner separation between the unsafe ffi code and rust implementation.
There is some bikeshedding left to be done: `InterfaceClassStruct` is quite clumsy, but reusing `ClassStruct` is not possible, as it is tailored towards object subclasses. We could call it `InterfaceStruct` to align it with `IsClass` ->`IsInterface` and similar traits that omit `Class`. Then we should also name `ObjectInterface::Class` `ObjectInterface::Interface` I suppose.
Do we need something like `glib::subclass::basic::ClassStruct` for `InterfaceClassStruct`? I would say we don't, as most interfaces define vfuncs anyway.
Closes #1382
=> glib: Decouple ObjectInterface impl from interface class struct

glib-macros/src/lib.rs, glib-macros/src/object_impl_attributes.rs, glib-macros/src/object_impl_attributes/interface.rs, glib-macros/src/object_impl_attributes/subclass.rs
Separates the parsing code from codegen, and unifies the parsing code to just one implementation.
This should make it easier to work on it in the future, in case we want to go that route.
=> glib-macros: Refactor parsing code of object_subclass/object_interface

examples/Cargo.toml, examples/README.md, examples/virtual_methods/cat.rs, examples/virtual_methods/main.rs, examples/virtual_methods/pet.rs, examples/virtual_methods/purrable.rs, examples/virtual_methods/tabby_cat.rs
Adds a very detailed example of virtual methods and interfaces. We already had one in gtk4, but not here. I also couldn't find any example for properly chaining up interface vfuncs.
The example is a bit elaborate, but I am convinced that every class here has some merit. It was for example unexpected to me that the interface had to be re-declared in the subclass a second time to override its vfunc, as this is not required for classes. I can however split it up if that is desired.
Some questions that came up:
- Should some of these `Ext` traits be sealed? They have a bound that is equal to their implementation, so I'm not entirely sure what that would accomplish.
-  All examples of subclassing I found put the class struct out of the implementation module. The few interface implementations I …
=> examples: Add example for custom class structs and virtual methods

glib-macros/src/properties.rs, glib-macros/tests/properties.rs, glib-macros/tests/test.rs, glib/src/main_context_futures.rs
* Fix clippy warnings in glib-macros/tests
* Annotate automatically generated property getters and setters with `#[allow(dead_code]`
=> Fix clippy warnings

glib/src/functions.rs
Please let me know if this would be a useful addition - I am currently porting [libipuz](https://gitlab.gnome.org/jrb/libipuz) to Rust, and need this function to do so.
I haven't fully looked at the tests and everything, let me know what else I need to implement to get this merged.
=> glib/functions: add compute_checksum_for_string

glib/src/match_info.rs
`FALSE` is returned both on errors when the `GError*` is set as well as if there is no further match, in which case the `GError*` is not set.
Change the return type from `Result<(), glib::Error>` to `Result<bool, glib::Error>` to be able to represent that and don't assert that either `TRUE` is returned or the `GError*` is set.
Fixes https://github.com/gtk-rs/gtk4-rs/issues/1749
=> glib: Fix `MatchInfo::next()` handling of returning `FALSE`

glib/src/value.rs
This allows converting a `Value` into a `SendValue` without statically knowing its type but is unsafe because the caller needs to ensure the contained type is actually `Send`.
This is slightly safer than going through `SendValue::unsafe_from(value.into_raw())`.
=> glib: Add unsafe `Value::into_send_value()`

.github/workflows/windows.yml
I think we are still using a pre-release version of glib... Update to the latest version.
=> ci: bump gvsbuild

glib/src/collections/strv.rs
This is especially useful when used in conjunction with gettext. E.g:
...
.buttons([gettext("_Cancel"), &gettext("_OK")])
=> strv: add From implementation from a String array

examples/gio_futures_await/main.rs, examples/gio_task/main.rs, gio/src/action_map.rs, gio/src/async_initable.rs, glib-macros/src/clone.rs, glib-macros/src/clone_old.rs, glib-macros/src/closure.rs, glib-macros/src/closure_old.rs, glib-macros/src/lib.rs, glib-macros/tests/clone.rs, glib-macros/tests/closure.rs, glib-macros/tests/test.rs, glib/src/gobject/signal_group.rs, glib/tests/clone.rs, glib/tests/log.rs, glib/tests/print.rs
This works correctly with rustfmt now, and thanks to using syn correctly also gives much better user experience with rust-analyzer.
Also the `closure!` macro now supports plain weak references too.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1394
=> Update `clone!` and `closure!` macro to new syntax

glib-macros/src/clone.rs, glib-macros/src/closure.rs, glib-macros/tests/test.rs
Wrapping through `IntoClosureReturnValue` is needed in this case.
=> glib-macros: Fix unit return in `closure!()` macro

gio/Gir.toml, gio/src/lib.rs, gio/src/prelude.rs, gio/src/socket_listener.rs
This object provides a `Stream` over which we can iterate in order to accept connections in an async environment.
This is analogous to the one provided by async-std's `TcpListener`.
This is an attempt at #1064. As I mention there, I think `SocketService` is the wrong abstraction to use in async so this is implemented for `SocketListener`, so that this `incoming()` is by itself an alternative to `SocketService`.
The type that we return here feels pretty awkward but it's what this returns. The pattern with the source object feels like another instance of something that makes sense without easy async but with async Rust you'd create multiple objects? But maybe I don't see other use-cases for it here.
=> gio: Add a method to get a stream of incoming connections to SocketListener

glib/src/collections/list.rs, glib/src/collections/slist.rs
=> Implement std::iter::Extend for glib::List

glib/sys/src/manual.rs
`G_VARIANT_TYPE_BYTE_STRING_ARRAY` is `"aay"` (`[[u8]]`), not `"ayy"` (`[u8]` + stray string `"y"`).
https://gitlab.gnome.org/GNOME/glib/-/blob/593b88bf1f21ee5fd261b84bf639ef1fa17f7a35/glib/gvarianttype.h#L249-254
=> glib-sys: Fix value of `G_VARIANT_TYPE_BYTE_STRING_ARRAY`

glib/src/collections/ptr_slice.rs, glib/src/collections/strv.rs
After creating a new memory allocation, [`StrV::reserve`](https://gtk-rs.org/gtk-rs-core/stable/0.20/docs/glib/collections/strv/struct.StrV.html#method.reserve) didn't properly null-terminate the underlying array. This could cause an undefined behavior in `g_strfreev` if the `StrV` was immediately dropped.
=> glib: Ensure NULL terminator is present after creating allocation in `{StrV,PtrSlice}::reserve`

glib/src/variant_dict.rs
While this method consumes a given `VariantDict`, the underlying object could still be accessed through other clones because of the reference counted clone semantics, which means it's unsound to use [`VariantDict::end_unsafe`](https://gtk-rs.org/gtk-rs-core/stable/0.20/docs/glib/struct.VariantDict.html#method.end_unsafe) here.
=> glib: Do not use `end_unsafe` in `<Variant as From<VariantDict>>::from`

glib-macros/src/properties.rs, glib-macros/tests/properties.rs
=> glib-macros: Do not emit import of `Property{Get,Set}` in `Properties` derive macro

glib/src/unicollate.rs, glib/tests/unicollate.rs
All that is guaranteed about them is that they give the correct order for the original strings when passed to strcmp().
Also add a separate integration test for this that calls setlocale() to get the default system locale. This makes sure that not just the "C" locale is selected, which returns literally the same string as collation key.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1504
=> glib: Collation keys are not necessary valid UTF-8

glib-macros/tests/properties.rs, glib/src/param_spec.rs
This makes it possible to pass a non-`'static` `&VariantTy` to [`ParamSpecVariant::builder`](https://gtk-rs.org/gtk-rs-core/stable/0.20/docs/glib/struct.ParamSpecVariant.html#method.builder) in `#[derive(Properties)]`. Example:
```rust
#[derive(Properties)]
#[properties(wrapper_type = super::Foo)]
pub struct Foo {
#[property(get, set, builder(&<Option<i32>>::static_variant_type()))]
variant: RefCell<Option<glib::Variant>>,
}
```
=> glib: Make `<Variant as HasParamSpec>::BuilderFn` generic over lifetimes

glib-macros/src/object_impl_attributes/subclass.rs
Mutable references to mutable statics are not only discouraged, they will also be removed in rust 2024
I have grepped the code for more of these, but didn't find any.
Closes #1516
=> glib-macros: Remove &mut to static mut in object_subclass

glib-macros/src/async_test.rs, glib-macros/src/lib.rs, glib/src/lib.rs
Added a procedural macro for async tests, wrapping them in `glib::MainContext`. 
Not sure if it's useful for others, but I found myself needing this occasionally. Feel free to reject if it's not a good fit.
=> glib-macros: add test macro for async-glib-context tests

examples/virtual_methods/cat.rs, examples/virtual_methods/pet.rs, examples/virtual_methods/purrable.rs
Separates out the examples as those don't introduce breaking changes.
See #1515
=> examples: Add stricter impl trait bounds

CHANGELOG.md, gdk-pixbuf/src/subclass/pixbuf_animation.rs, gdk-pixbuf/src/subclass/pixbuf_animation_iter.rs, gdk-pixbuf/src/subclass/pixbuf_loader.rs, gio/src/subclass/action_group.rs, gio/src/subclass/action_map.rs, gio/src/subclass/application.rs, gio/src/subclass/async_initable.rs, gio/src/subclass/initable.rs, gio/src/subclass/input_stream.rs, gio/src/subclass/io_stream.rs, gio/src/subclass/list_model.rs, gio/src/subclass/output_stream.rs, gio/src/subclass/seekable.rs, gio/src/subclass/socket_control_message.rs, glib-macros/tests/object_subclass_dynamic.rs, glib-macros/tests/properties.rs, glib/src/gobject/dynamic_object.rs, glib/src/subclass/object.rs, glib/src/subclass/type_module.rs, glib/src/subclass/type_plugin.rs, glib/tests/subclass_compiletest/04-auto-send-sync-with-send-sync-parent.rs, glib/tests/subclass_compiletest/05-no-auto-send-sync-with-non-send-sync-parent.rs, glib/tests/subclass_compiletest/05-no-auto-send-sync-with-non-send-sync-parent.stderr, glib/tests/subclass_compiletest/06-no-auto-send-sync-with-non-send-sync-ffi-parent.rs, glib/tests/subclass_compiletest/06-no-auto-send-sync-with-non-send-sync-ffi-parent.stderr
=> Add additional type bounds to Impl traits

gio/src/inet_address.rs
Removes use of unsafe code for conversion and implicitly fixes endianess
issues in conversion.
Fixes #1535
=> Safely and correctly convert InetAddress to IpAddr

.github/workflows/CI.yml, glib/src/bridged_logging.rs, glib/tests/bridged_logging.rs
=> Deduplicate metadata for structured logging

cairo/src/xcb.rs
cairo currently does not compile when using xcb and not using glib, because crate::Borrowed is not imported but is used. This fixes that.
```
> cd cairo/
> cargo c --no-default-features --features=xcb
error[E0412]: cannot find type `Borrowed` in this scope
--> cairo/src/xcb.rs:49:71
|
49 |     pub unsafe fn from_raw_borrow(ptr: *mut ffi::xcb_connection_t) -> Borrowed<XCBConnection> {
|                                                                       ^^^^^^^^ not found in this scope
|
help: consider importing this struct through its public re-export
|
5  + use crate::Borrowed;
|
<same error about 10 other times>
```
=> cairo/src/xcb.rs: use crate::Borrowed when not using glib

glib/src/object.rs
Emits errors such as these:
```
error[E0277]: the trait `glib::object::IsA<purrable::Purrable>` is not implemented for `tabby_cat::TabbyCat`
--> examples/virtual_methods/main.rs:38:30
|
38 |     let purrable = tabby_cat.upcast_ref::<Purrable>();
|                              ^^^^^^^^^^ requires `tabby_cat::TabbyCat` to be a GObject that can be cast as `purrable::Purrable`
|
= help: the trait `glib::object::IsA<purrable::Purrable>` is not implemented for `tabby_cat::TabbyCat`
= note: if this is your own object, use the `glib::wrapper!` macro to implement this trait: https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/macro.wrapper.html
= help: the following other types implement trait `glib::object::IsA<T>`:
`tabby_cat::TabbyCat` implements `glib::object::IsA<Object>` …
```
=> glib: Add unimplemented diagnostic to IsA linking to the wrapper macro

glib-macros/src/boxed_derive.rs, glib-macros/tests/test.rs, glib/src/collections/ptr_slice.rs, glib/src/collections/slice.rs
I.e. they're equal to their FFI representation, not equal to a pointer of their FFI representation.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1554
----
@pbor you introduced this in 84c951ef5a62. Sorry for not catching that. I'll backport this breaking change to the 0.20 branch and include it in the next bugfix release because this was simply wrong and could've only worked by chance (and usually involve memory corruption).
=> glib-macros: Derived boxed types are not TransparentPtrType but `TransparentType`

pango/Gir.toml, pango/src/auto/layout_line.rs, pango/src/layout.rs
The returned array has 2*n_ranges elements, not just n_ranges.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1563
=> pango: Fix `LayoutLine::x_ranges()` bindings

glib/src/object.rs
```
commit 84cd3fd35f5675f4aa882b47c237a24923122cd1
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Wed Nov 6 10:19:15 2024 +0200
glib: Also check for subtypes in `Object::has_property_with_type()`
commit 41daf6c82b0ed26b2b589ef2caed7b7e42cadc8c
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Wed Nov 6 10:17:00 2024 +0200
glib: Remove type parameter from `Object::has_property()` and add separate `has_property_with_type()`
Most of the time the property type is not interesting and the `None`
makes the code harder to understand. Having a separate, more descriptive
function for also checking the type seems better.
```
=> glib: Remove type parameter from `Object::has_property()` and add separate `has_property_with_type()` and check for subtypes

glib/src/subclass/object.rs, glib/src/subclass/signal.rs
It's only needed for overridden class handlers, not the default one.
Also add a test for overriding a signal class handler.
=> glib: Remove `SignalClassHandlerToken` from default class handler

examples/gio_dbus_register_object/main.rs, gio/Gir.toml, gio/src/auto/dbus_method_invocation.rs, gio/src/dbus_connection.rs, gio/tests/dbus_peer.rs
=> gio: Fix nullability of various DBus method call related parameters

gio/src/lib.rs
It was not exported at all before.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1597
=> gio: Export `RegistrationBuilder` from the crate root

gio/sys/src/manual.rs
See https://gitlab.gnome.org/GNOME/librsvg/-/issues/1126#note_2298554
Just in time for after the bugfix release... will do another one with just this later.
=> gio: Only provide UNIX mount compat API on UNIX platforms

glib/src/source.rs
able to specify priority
related: https://github.com/gtk-rs/gtk-rs-core/discussions/1613
=> glib: `unix_fd_add_full` and `unix_fd_add_local_full`

glib/src/object.rs
Fixes #1617
Not sure whether it would be better to remove the Default impl too, I've kept it for now.
=> glib: Remove SendWeakRef::new() because implementation is unsound

glib/src/object.rs
=> glib: Deprecate SendWeakRef::new() because implementation is unsound

examples/gio_dbus_register_object/main.rs, gio/src/subclass/application.rs
Using this vfunc makes exporting objects on the app's bus name much easier and more reliable.
I've rewritten the corresponding example to use these two methods, as the GIO docs recommend to use these vfuncs for object registration.  Also, registering an object in startup is prone to race conditions wrt to bus ownership as the object gets registered only after the application claimed the bus name.
=> Expose dbus_register and dbus_unregister vfuncs

gio/Gir.toml, gio/src/auto/subprocess_launcher.rs, gio/src/subprocess_launcher.rs
See #1638
This should be better than the existing bindings, but changing the API to something that accepts `&[impl AsRef<OsStr>]` would be preferable.
=> gio: Use manual env: &[OsString] parameter for SubprocessLauncher::set_environ

gio/src/cancellable_future.rs, gio/src/lib.rs
This type is effectively public, because it’s returned by `Cancellable::connect_cancelled`, but because it’s not re-exported it can’t be named, making it awkward to e.g. save it in a struct field.
Fixes GH-1649.
=> Re-export CancelledHandlerId

cairo/src/context.rs, cairo/src/device.rs, cairo/src/region.rs, cairo/src/surface.rs, cairo/src/surface_macros.rs, glib-macros/src/boxed_derive.rs, glib-macros/src/shared_boxed_derive.rs, glib/src/boxed.rs, glib/src/boxed_inline.rs, glib/src/collections/list.rs, glib/src/collections/ptr_slice.rs, glib/src/collections/slice.rs, glib/src/collections/slist.rs, glib/src/collections/strv.rs, glib/src/gstring.rs, glib/src/match_info.rs, glib/src/object.rs, glib/src/param_spec.rs, glib/src/shared.rs, glib/src/subclass/boxed.rs, glib/src/subclass/shared.rs, glib/src/translate.rs, glib/src/variant_type.rs
Fixes: https://github.com/gtk-rs/gtk-rs-core/issues/1663
Beside "`sed` changes", manual changes also include:
* `impl IntoGlibPtr<*mut c_char> for GString` requires inner `unsafe` block as calling `extern "C"` functions
* `pub unsafe trait RefCounted::into_raw` also changed removing `unsafe` requirement.
* This is a API (breaking/major) change
=> Remove unsafe interface requirement for into ptr conversion

pango/src/functions.rs
Fix for issue #1680.
The implementation of `&str::to_glib_none()` copies the string and causes an error, as the `item_text` argument is required to be a sub sequence of paragraph_text (if paragraph_text is not null). This is no longer the case after copying both strings.
The new wrapper uses `&str::as_bytes()` to prevent the copy. Both `pango_shape_full` and `pango_shape_with_flags` do not rely on null terminators when passing a non-negative length as argument, so this does not cause undefined behavior.
=> Fix bug in bindings of pango::shape_full and pango::shape_with_flags

glib/src/gstring.rs
It was previously not possible to create instances of this.
=> glib: Add From<AsRef<str>> impl for GStringPtr

gio/src/desktop_app_info.rs, gio/src/socket.rs, gio/src/unix_input_stream.rs, gio/src/unix_output_stream.rs, gio/tests/dbus_peer.rs, glib/src/functions.rs, glib/src/log.rs
This is the first and second commit of https://github.com/gtk-rs/gtk-rs-core/pull/871.
=> Port some functions to safe-io: pt I

cairo/src/surface.rs, gdk-pixbuf/src/pixbuf.rs, gio/src/input_stream.rs, gio/src/socket.rs
=> gio: Use `OwnedSocket` / `BorrowedSocket` for Windows APIs on GSocket

.github/workflows/CI.yml, Cargo.toml, README.md, cairo/README.md, gdk-pixbuf/README.md, gio/Gir.toml, gio/README.md, gio/src/application.rs, gio/src/auto/application.rs, gio/src/gio_future.rs, gio/src/subclass/application.rs, glib-build-tools/README.md, glib/README.md, glib/src/exit_code.rs, glib/src/lib.rs, glib/src/source_futures.rs, graphene/README.md, pango/README.md, pangocairo/README.md, tests/two-levels-glib-dependent/glib-dependent-dependent/Cargo.toml, tests/two-levels-glib-dependent/gstreamer/Cargo.toml, tests/two-levels-glib-dependent/gtk/Cargo.toml
Add a manual override to use `glib::ExitCode` instead of the gir generated `i32` return value for `connect_command_line` and `connect_handle_local_options`.
This fixes #1691
=> gio: Return `glib::ExitCode` from `gio::Application` signal handlers

glib/gobject-sys/Gir.toml
That feature should not even exist at all. The problem comes from <https://github.com/gtk-rs/gir/blob/main/src/codegen/sys/cargo_toml.rs#L126-L136> but as i don't have the time to track it down, let us work around it for now
=> gobject: Work around wrongly added v2_82 feature

gio/Gir.toml, gio/src/auto/functions.rs, gio/src/content_type.rs, gio/src/lib.rs, gio/tests/content_type.rs
Related: https://github.com/gtk-rs/gtk-rs-core/issues/1257
In C, `g_content_type_guess` supports passing NULL to the `data` parameter which makes it guess the content type based on the filename only.
So, add a manually written `content_type_guess` allowing `Option` for the `data` parameter. This is a stopgap until `gir` can generate the optional parameter for these cases.
This is an API break in some cases, but should continue to compile in most cases.
=> gio: manually implement content_type_guess

Cargo.lock, gio/Cargo.toml, gio/src/subclass/file_monitor.rs, gio/src/subclass/mod.rs
Allow custom implementation of gio::FileMonitor
=> Add gio::FileMonitor subclass

glib-macros/src/lib.rs
When using the `Properties` macro with enum types that derive `Enum`, the default value must be explicitly set using `#[property(builder(...))]`.
=> Document requirement for explicit default in `Enum` properties

gio/src/subclass/mod.rs, gio/src/subclass/vfs.rs, glib/src/collections/mod.rs, glib/src/collections/strv.rs, glib/src/lib.rs
Allow custom implementation of gio::Vfs
=> Add gio::Vfs subclass

Dockerfile
Pulls gi-docgen which pulls a ton of useless bits
=> image: Disable docs for gdk-pixbuf as well

cairo/Cargo.toml, cairo/src/lib.rs, cairo/sys/Cargo.toml, cairo/sys/src/lib.rs
In [Prince](https://www.princexml.com/) we use a custom build of Cairo that is built with a shared configuration across platforms. This configuration does not enable Quartz surfaces, since we don't use them. When trying to use this build of cairo from cairo-rs on macOS we get these linker errors:
```
Making Mercury/hlc.par.gc/aarch64-apple-darwin23.3.0/Mercury/bin/prince
Undefined symbols for architecture arm64:
"_cairo_quartz_surface_create", referenced from:
cairo::quartz_surface::QuartzSurface::create::hd523178627094f5c in libfontcode.a[26](cairo-985f17ee8c3b353d.cairo.82c62016cb75f98b-cgu.7.rcgu.o)
"_cairo_quartz_surface_create_for_cg_context", referenced from:
cairo::quartz_surface::QuartzSurface::create_for_cg_context::hfd933effa02b3a48 in …
```
=> Add cargo feature for quartz surface

glib/src/gstring.rs
[`g_value_take_boxed`](https://docs.gtk.org/gobject/method.Value.take_boxed.html) takes full ownership of a provided object, so we should convert `GString`s into `*mut c_char`s by `into_glib_ptr`.
Fixes the segfault that occurs when releasing the `Value` created by converting from `Vec<GString>`.
=> glib: Fully transfer ownership in `<Value as From<Vec<GString>>>::from`

gio/src/dbus_method_invocation.rs
Without `Self::` this generates an error and does not link to the other method.
=> gio: update doc links in `DBusMethodInvocation`

gio/Gir.toml, gio/src/auto/file_enumerator.rs, gio/src/file_enumerator.rs, gio/src/subclass/file_enumerator.rs, gio/src/subclass/mod.rs
Allow custom implementation of gio::FileEnumerator
=> Add gio::FileEnumerator subclass

glib-macros/src/lib.rs, glib-macros/src/properties.rs, glib-macros/tests/properties.rs, glib/src/param_spec.rs
Given a struct like
```rust
#[derive(Copy, Default, Clone, Debug, PartialEq, Eq, glib::Enum)]
#[enum_type(name = "SimpleEnum")]
pub enum SimpleEnum {
#[default]
One,
Two,
}
```
you currently have to specify the default value as part of the param spec builder, e.g.
```rust
#[property(get, set, builder(SimpleEnum::One))]
fenum: RefCell<SimpleEnum>,
```
With this PR, we allow for that to change to 
```rust
#[property(get, set, default)]
fenum: RefCell<SimpleEnum>,
```
as discussed in #930. This started with what @ranfdev wrote though it changed a little bit.
It's still a bit messier than I was hoping as you still have a few different ways of setting the default value, you can have
#[property(default)]
#[property(builder(Type::Default))]
which is fine for compat and because not every enum has …
=> Allow specifying a default via `Default` in a field within `Properties`

gio/src/file_descriptor_based.rs
Seems like an obvious thing to do, and is necessary to safely get an FD out of a GIO file input stream, as far as I can see.
=> Impl AsFd for FileDescriptorBased

glib/src/thread_guard.rs
When a struct's `Drop::drop` impl panics, Rust will still drop the fields of the struct before continuing to unwind[^1].
`glib::thread_guard::ThreadGuard<T>` currently holds a `value: T`, so if a `ThreadGuard` is dropped on the wrong thread, its drop impl will panic, and then the drop glue will attempt to drop the `value: T` field before continuing to unwind. This violates the purpose of `ThreadGuard` as it allows accessing the `T` on a thread other than the one it was created on (in `T`'s `Drop` impl).
This PR wraps the `value` field in `ManuallyDrop` so it will not be automatically dropped, and drops it manually in `ThreadGuard`'s `Drop::drop` impl if it is on the correct thread.
<details> <summary>Examples showing issue</summary>
```Rust
use glib::thread_guard::{ThreadGuard, …
```
=> glib: Don't drop `T` if `ThreadGuard<T>` is dropped on the wrong thread.

glib/src/collections/list.rs, glib/src/collections/slist.rs
One more level of pointer indirection is needed to get the item from the list.
CC @A6GibKm
=> glib: Fix segfault in `List::retain()`

gio/Gir.toml, gio/src/application_command_line.rs, gio/src/auto/application_command_line.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/1694#issuecomment-3154057825
Did you think of something like this? @swsnr @sdroege
=> Use `glib::ExitCode` for `gio::ApplicationCommandLine::{exit_status,set_exit_status}`

gio/Gir.toml, gio/src/application_command_line.rs, gio/src/lib.rs, gio/src/prelude.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/1779#issuecomment-3167703612
@sdroege Let's do it properly now. (And wait for most of the CI.)
=> gio: Fix ApplicationCommandLineExtManual draft

glib/src/variant.rs
Seems natural since it's just a thin wrapper around String.
Let's us do `format!("Object path {path}")` instead of `format!("Object path {}", path.as_str())` which is handy for logging in particular.
=> Implement Display for ObjectPath

Cargo.toml, gio/Cargo.toml, glib-macros/Cargo.toml, glib-macros/src/utils.rs, glib/Cargo.toml, glib/src/functions.rs, glib/src/lib.rs, glib/src/thread_pool.rs, glib/tests/clone.rs
Allow to build glib crates with lower external dependencies:
- make "proc-macro-crate" optional in glib-macros
- make "futures*" crates optional in glib
=> Lower the amount of required dependencies

glib/src/error.rs
Add a constructor to create errors from a domain quark and code, useful when creating errors with the same domain/code but different messages as we can't get a rust type which implements the `ErrorDomain` in that case.
This also adds a code() getter method to retrieve the error code.
=> glib: Add Error::with_domain constructor and code getter
