gtk-rs/gtk-rs-core

- gio/src/subclass/input_stream.rs
- gio/src/subclass/io_stream.rs
- gio/src/subclass/output_stream.rs
- gio/src/subclass/seekable.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/57
> gio: Only assign to `GError**`s if they're not `NULL`

- README.md
This is done to mimic the README of gtk4-rs
> Readme: Add links to examples and api

- .github/ISSUE_TEMPLATE/asking-for-help.md
Same as https://github.com/gtk-rs/gtk3-rs/pull/533.
> Update issue templates

- glib/Gir.toml
- glib/src/auto/main_context.rs
- glib/src/main_context.rs
- glib/src/main_context_channel.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/71
> glib: Implement main context acquire guard type

- glib/src/object.rs
Continuation of https://github.com/gtk-rs/gtk3-rs/pull/504
> glib: bind [freeze|thaw]_notify

- glib-macros/tests/test.rs
This test was written to illustrate issue #8
> Add a subclassable test

- .github/workflows/CI.yml
Same as https://github.com/gtk-rs/gtk3-rs/pull/540.
> Add doc alias check

- cairo/src/enums.rs
- cairo/src/error.rs
Part of https://github.com/gtk-rs/checker/pull/24.
> Add missing doc aliases on variants

- glib/src/lib.rs
- glib/src/win32.rs
- glib/sys/Gir.toml
- glib/sys/src/manual.rs
Partially fixes https://github.com/gtk-rs/gtk-rs-core/issues/2
> Manually bind g_win32_get_package_installation_directory_of_module

- pango/src/attribute.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/98.
> Add missing binding for pango::Attribute::new_shape

- .github/workflows/docs.yml
the gir-rustdoc script handles that for us already
> CI docs: drop manual rustdocflags

- glib/src/lib.rs
- glib/src/value.rs
> Create Boxed(Value) newtype for Boxed GValue

- .github/workflows/CI.yml
> Run tests of sys crates in CI action

- .github/ISSUE_TEMPLATE/blank-issue.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request-or-missing-binding.md
The current issue template was clearly lacking. I added a few others to fill this void.
> Add more issues templates

- glib-macros/src/lib.rs
> Add missing information for glib clone macro

- Dockerfile
it would be used by the docs job to grab gtk-rs's logo/favicons
> image: pre-install wget

- .github/workflows/CI.yml
- .github/workflows/docs.yml
To be merged once #141 is merged
> CI: use the core image

- glib/src/variant.rs
Backport of https://github.com/gtk-rs/gtk-rs-core/pull/165
> glib: Fix invalid types let from_variant panic

- glib/tests/value.rs
> Replace unneeded doc comments with comments

- .github/workflows/CI.yml
- README.md
- cairo/README.md
- gdk-pixbuf/README.md
- gio/README.md
- glib/README.md
- graphene/README.md
- pango/README.md
- pangocairo/README.md
> Bump min required version to 1.53.0

- pango/src/attribute.rs
I'm not sure why this wasn't already added.  Maybe there's something that I'm missing.
> add pango_attr_font_desc_new

- .github/workflows/CI.yml
- README.md
- cairo/README.md
- cairo/src/lib.rs
- gdk-pixbuf/README.md
- gdk-pixbuf/src/lib.rs
- gio/README.md
- gio/src/lib.rs
- glib/README.md
- glib/src/lib.rs
- graphene/README.md
- graphene/src/lib.rs
- pango/README.md
- pango/src/lib.rs
- pangocairo/README.md
- pangocairo/src/lib.rs
Similar to https://github.com/gtk-rs/gtk3-rs/pull/613.
> Merge README files and crate documentation

- glib/src/variant.rs
- glib/src/variant_dict.rs
In ostree/rpm-ostree we use GVariant extensively and particularly
`a{sv}`s.  I have this helper trait
https://github.com/ostreedev/ostree-rs-ext/blob/6fcdde1697a851f9c29d9f8b15d77e114a7a5ae7/lib/src/variant_utils.rs#L32
but we can do better by offering an API equivalent to
`lookup()` + `Variant::get()` that returns the native type.
Plus for `Variant` it's often convenient to have a version that
returns a `Result<T>` with a useful error message about
the actual+expected types.
---
> Variant,VariantDict: More type lookup methods

- pango/src/attribute.rs
- pango/src/color.rs
- pango/src/lib.rs
- pango/src/prelude.rs
This is a port of my old PR gtk-rs/gtk3-rs#400.  I believe that I took into account all of the feedback from that PR.
> be able to inspect pango attribute types and downcast them

- glib/src/variant.rs
This adds an additional method to retrieve child value from a
container in a fallible way. It returns an optional type in order
to avoid panics if the input does not meet the requirements.
> glib/variant: add fallible child-value getter

- glib/src/variant.rs
Similarly to how we have a `str()` method which avoids copying
string data just to read it, add a method to access a byte array
directly.  Right now, dealing with GVariant type `ay` is extremely
expensive because we'll end up heap allocating a variant for *each
byte* whether one does `let data: Vec<u8> = v.get()` or iterates.
Note that following previous design discussion, this API returns
`Result` and not `Option`.
> variant: Add a `bytes()` method.

- glib/src/lib.rs
- glib/src/unicollate.rs
Backport collation API to 0.14
> glib: add manual bindings for collation utils

- gio/src/settings.rs
- glib/src/lib.rs
- glib/src/variant.rs
- glib/src/variant_iter.rs
- glib/src/variant_type.rs
I'm planning to do another bugfix release after this.
> 0.14 backports

- glib/src/object.rs
- glib/src/wrapper.rs
Handling object wrappers with or without `@extends` and with or without `@implements` in one variant is problematic, since a comma between the two is necessary if and only if both are used.
But assuming no issues turn up, this should be a good improvement making this a fair bit simpler.
> glib: Merge variants of `wrapper!` as much as possible

- pango/src/attribute.rs
This would allow us to modify the various attributes without upcasting/downcasting
> pango: implement DerefMut for Attribute

- glib/src/param_spec.rs
Create two variants, one for a Class & the other for an interface.
We can't make them into one call as we will have to lose the IsInterface/IsClass checks
Fixes #201
> glib: add simpler variants of ParamSpec::new_override

- pango/Cargo.toml
> pango: add missing v1_50 feature

- pango/Gir.toml
- pango/src/auto/matrix.rs
- pango/src/lib.rs
- pango/src/matrix.rs
> Add missing Matrix methods

- gio/src/file.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/326
> gio: Make progress callback in `File::copy_async` optional

- glib/src/variant.rs
In ostree, we heavily use `a{sv}` and further we compute
cryptographic checksums over them.  It is hence important for
reproducibility that we insert values in a defined (sorted)
order.
Expressing this by serializing a `BTreeMap` in the same way we
support `HashMap` fixes this.
> variant: Add support for `BTreeMap`

- gio/src/settings.rs
- glib/Gir.toml
- glib/src/auto/enums.rs
- glib/src/auto/mod.rs
- glib/src/variant.rs
- glib/src/variant_dict.rs
- glib/src/variant_iter.rs
- glib/src/variant_type.rs
- glib/sys/src/manual.rs
This should lower the number of allocations a bit.
> glib: Lots of `Variant` / `VariantType` improvements

- glib/src/enums.rs
- glib/src/lib.rs
Less pointer wrapping and fewer allocations, and better `Debug` impl.
> glib: Simplify enum/flags class implementation

- gio/src/subclass/action_group.rs
- gio/src/subclass/action_map.rs
- gio/src/subclass/initable.rs
- gio/src/subclass/list_model.rs
- gio/src/subclass/seekable.rs
- glib/src/subclass/object.rs
- glib/src/subclass/types.rs
Similar to the simplification made to IsSubclassable.
> simplify IsImplementable implementations

- glib/Gir.toml
- glib/src/auto/date_time.rs
- glib/src/auto/time_zone.rs
- glib/src/date.rs
- glib/src/date_time.rs
- glib/src/param_spec.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/object.rs
- glib/src/thread_pool.rs
> Rename various constructors for consistency

- glib/src/boxed.rs
- glib/src/boxed_inline.rs
- glib/src/object.rs
- glib/src/shared.rs
This time it's hopefully all correct, for real. Third time!
> glib: Fix FromValue impls for &Boxed, &Shared and &Object

- glib-macros/src/boxed_derive.rs
- glib-macros/src/enum_derive.rs
- glib-macros/src/error_domain_derive.rs
- glib-macros/src/flags_attribute.rs
- glib-macros/src/lib.rs
- glib-macros/src/shared_boxed_derive.rs
- glib-macros/src/utils.rs
- glib-macros/src/variant_derive.rs
- glib-macros/tests/test.rs
- glib/src/lib.rs
- glib/src/subclass/boxed.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/shared.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/343
> Update macro syntax for enum, flags, boxed, and variant

- glib/README.md
See https://gtk-rs.org/gtk-rs-core/git/docs/glib/index.html#under-the-hood
> glib: fix broken link

- glib/src/subclass/signal.rs
The order of the user data tuple was mixed up and one layer of
additional pointer indirection was used.
Also the closure was boxed twice, which was unnecessary.
----
CC @rafaelcaricio
> glib: Fix accumulator trampoline in signals defined from Rust

- glib/src/subclass/mod.rs
Ups, I didn't think of this before
> glib: add ObjectSubclassIsExt to the prelude

- gio/src/list_store.rs
> gio: impl std::iter::Extend for gio::ListStore

- gio/src/list_store.rs
This also allows to use iterators over references of objects.
Also add a test for `extend()`.
----
See https://github.com/gtk-rs/gtk-rs-core/commit/277b94f0edecbee063f2ad12093e346868c8f8ef#r62142353
CC @ranfdev
> gio: Implement `Extend` on `ListStore` for `AsRef<Object>`

- gio/src/subclass/action_group.rs
- gio/src/subclass/action_map.rs
- gio/src/subclass/application.rs
- gio/src/subclass/initable.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/io_stream.rs
- gio/src/subclass/list_model.rs
- gio/src/subclass/output_stream.rs
- gio/src/subclass/seekable.rs
- glib/src/subclass/object.rs
- glib/src/subclass/types.rs
As discussed in https://github.com/gtk-rs/gtk4-rs/pull/776
> glib: Rename `impl_` to `imp`

- examples/gio_task/file_size/ffi.rs
- examples/gio_task/file_size/mod.rs
- gio/src/read_input_stream.rs
- gio/src/subclass/initable.rs
- gio/src/subclass/output_stream.rs
- gio/src/task.rs
- gio/src/write_output_stream.rs
- glib-macros/tests/test.rs
- glib/src/boxed_any_object.rs
- glib/src/subclass/object.rs
- glib/src/subclass/types.rs
- tests/two-levels-glib-dependent/glib-dependent-dependent/src/lib.rs
Fixes CI for https://github.com/gtk-rs/gtk4-rs/pull/776
> rename missed impl_ to imp

- .github/workflows/CI.yml
No idea why this part got removed from the CI..
> CI: run tests as well

- cairo/src/device.rs
- cairo/src/region.rs
- gio/src/subclass/action_map.rs
- glib/src/variant.rs
I'll need to send a PR to gir too to fix the missing `#[must_use]` in the auto code.
> Fix new clippy lints

- glib/src/log.rs
> Reduce allocations in `g_log` bindings

- pango/src/rectangle.rs
> pango: add setters for Rectangle

- gio/src/task.rs
Module level documentation is not picked up by the gtk-rs doc tool.
> gio: move task docs on the structs

- glib-macros/src/object_subclass_attribute.rs
- glib/src/subclass/types.rs
It's not much... I was browsing the glib-macros folder to see how things were implemented and I thought some things could be refactored a bit.
I've reduced the generated code by putting the TypeData literal in another module.
> Smaller subclass macro

- gio/src/gio_future.rs
This is unnecessary now because GIO-style async functions don't require
`Send` for their callback anymore, and it also removes the two layers of
checks to enforce at runtime that everything is handled on the same
thread.
----
This should not be backported as it's breaking backwards compatibility.
> gio: Don't implement `Send` on `GioFuture` anymore

- glib/src/bridged_logging.rs
And with that I would make bugfix releases once merged.
> 0.15 backports

- cairo/src/image_surface.rs
- cairo/src/image_surface_png.rs
- cairo/src/pdf.rs
- cairo/src/ps.rs
- cairo/src/stream.rs
- cairo/src/svg.rs
- gdk-pixbuf/src/pixbuf.rs
- gio/src/file.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/output_stream.rs
- gio/src/unix_socket_address.rs
- glib/src/bytes.rs
- glib/src/closure.rs
- glib/src/collections.rs
- glib/src/enums.rs
- glib/src/gstring.rs
- glib/src/gstring_builder.rs
- glib/src/subclass/signal.rs
- glib/src/value_array.rs
- glib/src/variant.rs
- glib/src/variant_type.rs
Passing NULL to `slice::from_raw_parts` is invalid.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/532
> Handle empty slices correctly

- glib/src/lib.rs
- glib/src/prelude.rs
- glib/src/types.rs
> glib: add trait `StaticTypeExt` with method `type_ensure`

- cairo/Cargo.toml
- cairo/src/context.rs
- cairo/src/matrices.rs
- cairo/src/rectangle.rs
- cairo/src/rectangle_int.rs
- cairo/src/surface.rs
- cairo/src/utils.rs
- cairo/sys/src/lib.rs
- pango/src/layout.rs
> Remove remaining public fields

- cairo/src/context.rs
- cairo/src/font/font_extents.rs
- cairo/src/font/glyph.rs
- cairo/src/font/mod.rs
- cairo/src/font/scaled_font.rs
- cairo/src/font/text_cluster.rs
- cairo/src/font/text_extents.rs
- cairo/src/matrices.rs
- cairo/sys/src/lib.rs
>  Fix cairo FFI types name

- glib-macros/src/closure.rs
- glib-macros/tests/test.rs
- glib/src/object.rs
This also saves us from doing an extra `ref`/`unref` on watched objects when calling those closures
> glib-macros: Pass a pointer for watched objects into closure macro

- glib/src/param_spec.rs
Small refactor to reduce code duplication.
> Smaller spec numeric definition

- glib/src/value.rs
solves #576 and also lets me correctly handle `ParamSpecUnichar` in #494
> impl `ToValue`, `FromValue` for char

- glib/src/value.rs
Previously it was always using the `GenericValueTypeChecker`, which
would only check for the `GType` but not for any possible additional
constraints of the given type.
> glib: Use the correct value type checker for optional types

- cairo/src/font/font_options.rs
- gdk-pixbuf/Gir.toml
- gdk-pixbuf/src/auto/pixbuf_format.rs
- gio/Gir.toml
- gio/src/auto/unix_mount_entry.rs
- gio/src/auto/unix_mount_point.rs
- pango/Gir.toml
- pango/src/attribute.rs
- pango/src/auto/attribute.rs
- pango/src/auto/font_description.rs
- pango/src/auto/glyph_string.rs
- pango/src/auto/tab_array.rs
- pango/src/language.rs
These should work provided the type is not refcounted, contains no refcounted types inside it, and contains no thread local data. It would be nice to find a way to test this...
> Use Send+Sync for more Boxed types

- glib/src/variant.rs
`g_variant_print` was only indirectly exposed via `Display`, and its complimentary `g_variant_parse` was entirely missing - so this exposes both explicitly and then uses them to impl `Display`/`FromStr`
Some considerations:
- `g_variant_parse` has an `endptr` argument that can be used to check if the entire string was parsed, or otherwise where the variant stops and the rest of the string continues. I did not expose this functionality here.
- Using the abstraction which now returns a `String` instead of `GString` presumably introduces an extra allocation to the `Display::fmt` impl compared to before?
> glib: print and parse for Variant

- glib-macros/tests/test.rs
> glib-macros: Fix clippy lints

- cairo/src/lib.rs
- glib/src/boxed_inline.rs
> Implement ValueTypeOptional for BoxedInline and cairo types

- gdk-pixbuf/Gir.toml
See https://gtk-rs.org/gtk-rs-core/git/docs/gdk_pixbuf/struct.Pixbuf.html#creating-new-pixbuf
> gdk_pixbuf: opt-in for gi-docgen

- gio/src/list_store.rs
> remove extend_from_slice position subtraction, add test

- gio/src/file_attribute_info.rs
- glib/src/key_file.rs
> Remove more redundant null checks

- gio/src/cancellable.rs
I'm not sure if I got it right
> gio: Add local variant for connect_cancelled

- gio/src/list_model.rs
- gio/src/list_store.rs
It's me with another take on #204.
> impl fallible IntoIterator for ListModel,ListStore

- glib/src/object.rs
Successor to https://github.com/gtk-rs/gtk-rs-core/pull/429
I hope all concerns have been addressed :)
>  glib: Add WeakRefNotify (v2)

- examples/gio_task/file_size/ffi.rs
- gio/src/subclass/initable.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/io_stream.rs
- gio/src/subclass/output_stream.rs
- gio/src/subclass/seekable.rs
- glib/src/boxed.rs
- glib/src/boxed_inline.rs
- glib/src/error.rs
- glib/src/gstring.rs
- glib/src/object.rs
- glib/src/translate.rs
- glib/src/variant_type.rs
Part of https://github.com/gtk-rs/gtk-rs-core/issues/50.
> Add ToGlibPtrMove trait

- glib/src/variant_type.rs
And add some assertions against `NULL` pointers in a few places.
> glib: Use `ptr::NonNull` for `VariantType` pointer storage

- .github/workflows/image.yml
> CI: update the gh-package job

- .github/workflows/image.yml
- Dockerfile
This one finally seems to work: https://github.com/jf2048/gtk-rs-core/runs/6430974746
> ci: push image to github container repository

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- .github/workflows/windows.yml
Ref: https://github.com/gtk-rs/gtk-rs-core/pull/688#discussion_r874468595
> ci: use set-safe-directory for gtk-rs/checker checkout

- cairo/Cargo.toml
- cairo/src/font/font_face.rs
- cairo/src/lib.rs
> cairo: Use freetype-sys instead of freetype.

- glib/src/gobject/binding_group.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/664.
> Fix GBindingGroup bindings

- gio/src/read_input_stream.rs
- gio/src/write_output_stream.rs
- glib/src/signal.rs
- glib/src/subclass/object.rs
Very boring PR. The most interesting change is the one in the docstring.
> Use RefCell::take() when possible

- pango/Gir.toml
- pango/src/auto/functions.rs
- pango/src/functions.rs
They're modified by the function.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/727
> pango: Mark parameters to `extents_to_pixels()` as mutable

- glib/Gir.toml
- glib/src/auto/enums.rs
- glib/src/auto/mod.rs
- glib/src/convert.rs
- glib/src/lib.rs
- glib/src/translate.rs
- Is there a better name for `CvtError`?
- Maybe some of these should be in utils.rs?
> glib: bind iconv functions

- glib/src/param_spec.rs
- glib/src/prelude.rs
cc @ranfdev 
Similar to what we have in `SignalBuilder`
> glib: Add flag setters to ParamSpec builders

- cairo/src/user_data.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/740
> cairo: Don't leak user data if setting it failed

- glib/src/variant.rs
> glib: Variant wrapper types for handles, object paths and signatures

- cairo/src/device.rs
- gio/src/application.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/751
> Add `#[must_use]` to guard objects

- gio/src/task.rs
Corresponds to https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2899
> gio: make Task::cancellable return Option

- gio/src/dbus_node_info.rs
- gio/src/lib.rs
- glib/src/collections.rs
This exposes fields as functions:
- path
- interfaces
- nodes
> Expose some fields of GDBusNodeInfo

- gio/src/dbus_node_info.rs
- gio/src/file_attribute_info_list.rs
- glib/src/boxed.rs
- glib/src/boxed_inline.rs
- glib/src/byte_array.rs
- glib/src/bytes.rs
- glib/src/closure.rs
- glib/src/collections.rs
- glib/src/date_time.rs
- glib/src/param_spec.rs
- glib/src/shared.rs
- glib/src/variant.rs
- pango/src/layout.rs
This will probably need changes in gtk/gstreamer too
> Implement more FFI translation traits for shared types

- glib/src/gobject/binding.rs
- glib/src/object.rs
Not sure about the naming though :)
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/382
> glib/BindingBuilder: add concrete type based transform setters

- gio/src/read_input_stream.rs
- gio/src/subclass/action_group.rs
- gio/src/subclass/action_map.rs
- gio/src/subclass/application.rs
- gio/src/subclass/async_initable.rs
- gio/src/subclass/initable.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/io_stream.rs
- gio/src/subclass/list_model.rs
- gio/src/subclass/output_stream.rs
- gio/src/subclass/seekable.rs
- gio/src/write_output_stream.rs
- glib-macros/src/clone.rs
- glib-macros/src/closure.rs
- glib-macros/src/lib.rs
- glib-macros/src/object_subclass_attribute.rs
- glib-macros/tests/clone.rs
- glib/src/gobject/binding.rs
- glib/src/gobject/binding_group.rs
- glib/src/lib.rs
- glib/src/object.rs
- glib/src/subclass/mod.rs
- glib/src/subclass/object.rs
- glib/src/subclass/object_impl_ref.rs
- glib/src/subclass/types.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/773
> Change *Impl trait methods to only take &self and not Self::Type in addition

- pangocairo/Gir.toml
- pangocairo/src/auto/font_map.rs
- pangocairo/src/auto/functions.rs
- pangocairo/tests/iterators.rs
> pangocairo: Trust upstream nullable annotations for return values

- glib/src/enums.rs
not building:
error: lifetime may not live long enough
--> glib/src/enums.rs:290:9
|
285 | unsafe impl<'a> FromValue<'a> for &EnumValue {
|             -- lifetime `'a` defined here
...
288 |     unsafe fn from_value(value: &'a Value) -> Self {
|                                               ---- return type is &'1 EnumValue
289 |         let (_, v) = EnumValue::from_value(value).unwrap();
290 |         v
|         ^ associated function was supposed to return data with lifetime `'1` but it is returning data with lifetime `'a`
> implement FromValue on EnumValue

- cairo/src/rectangle.rs
- glib/src/gobject/binding.rs
- glib/src/gobject/binding_group.rs
- glib/src/object.rs
@bilelmoussaoui anything else pending?
> 0.16 backports

- gio/src/subclass/action_group.rs
- gio/src/subclass/action_map.rs
- gio/src/subclass/application.rs
- gio/src/subclass/async_initable.rs
- gio/src/subclass/initable.rs
- gio/src/subclass/input_stream.rs
- gio/src/subclass/io_stream.rs
- gio/src/subclass/list_model.rs
- gio/src/subclass/output_stream.rs
- gio/src/subclass/seekable.rs
- glib/src/gobject/binding.rs
- glib/src/gobject/binding_group.rs
- glib/src/subclass/object.rs
- glib/src/subclass/object_impl_ref.rs
- glib/src/subclass/types.rs
It's doing the same thing and is shorter.
> Move from `imp.instance()` to `imp.obj()`

- gdk-pixbuf/src/lib.rs
- gdk-pixbuf/src/pixbuf_animation_iter.rs
- gdk-pixbuf/src/subclass/mod.rs
- gdk-pixbuf/src/subclass/pixbuf_animation.rs
- gdk-pixbuf/src/subclass/pixbuf_animation_iter.rs
- gdk-pixbuf/src/subclass/pixbuf_loader.rs
> gdk-pixbuf: Add subclassing support

- cairo/src/device.rs
- cairo/src/enums.rs
- cairo/src/stream.rs
Should fix the last of the CI check warnings, aside from the broken doc links
> cairo: fix some misc warnings

- gio/src/gio_future.rs
Needed for https://github.com/gtk-rs/gir/pull/1411
> gio: Add a GioInfaliableFuture

- glib/src/gstring.rs
> glib: Add GStr::from_ptr_lossy() and GString::from_ptr_lossy() and implement From<&GStr> and From<GString> for Cow<GStr>

- cairo/src/context.rs
- cairo/src/device.rs
- cairo/src/matrices.rs
- cairo/src/rectangle.rs
- cairo/src/rectangle_int.rs
- cairo/src/region.rs
- cairo/src/surface.rs
- cairo/src/surface_macros.rs
- cairo/src/xcb.rs
- gio/src/io_extension.rs
- gio/src/io_extension_point.rs
- glib-macros/src/boxed_derive.rs
- glib-macros/src/shared_boxed_derive.rs
- glib/src/boxed.rs
- glib/src/boxed_inline.rs
- glib/src/gstring.rs
- glib/src/object.rs
- glib/src/param_spec.rs
- glib/src/shared.rs
- glib/src/translate.rs
- glib/src/types.rs
- glib/src/value_array.rs
- glib/src/variant_type.rs
- pango/src/attr_class.rs
- pango/src/attr_iterator.rs
- pango/src/glyph_item_iter.rs
- pango/src/script_iter.rs
See individual commits.
CC @jf2048
> Various `Stash` / `to_glib_none()` related optimizations and bugfixes

- gio/Gir.toml
- gio/src/action_entry.rs
- gio/src/action_map.rs
- gio/src/auto/simple_action.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/845
> ActionEntry: take proper types instead of strings

- gio/src/subclass/async_initable.rs
Use CancellableFuture to clean up the code a little
> gio: simplify async initable

- Dockerfile
Needed for https://github.com/gtk-rs/gtk4-rs/pull/1268
> Enable introspection

- glib/src/param_spec.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/502
> glib: Add `ParamSpec::is()` helper function

- gdk-pixbuf/Gir.toml
- gdk-pixbuf/src/auto/pixbuf.rs
- gdk-pixbuf/src/auto/pixbuf_format.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/789
> gdk-pixbuf: Trust return value nullability

- gdk-pixbuf/src/pixbuf_animation_iter.rs
- gdk-pixbuf/src/subclass/pixbuf_animation.rs
- gdk-pixbuf/src/subclass/pixbuf_animation_iter.rs
> gdk-pixbuf: Fix time related types

- glib/src/collections/strv.rs
- glib/src/gstring.rs
- glib/src/key_file.rs
Since this is an owned type this is more consistent.
> Rename GStrPtr to GStringPtr

- gio/src/list_store.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/951
> gio: implement FromIterator for ListStore

- glib-macros/src/properties.rs
- glib-macros/tests/properties.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/957
> Support `default = ...` in the properties macro

- glib-macros/src/properties.rs
- glib-macros/tests/properties.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/946
> macros: support overrides in the properties macro

- gio/src/list_model.rs
Panic if the wrong type is requested, this is more ergonomic and asking for the wrong type is a programmer error.
> gio: make ListModel::iter() infallible

- glib-macros/src/properties.rs
Before: "Can't convert glib::value to property type: UnexpectedNone"
After: "Invalid conversion from `glib::value::Value` to `alloc::string::String` inside setter for property `bar`: UnexpectedNone'"
CC: @bilelmoussaoui
> Improve conversion errors for setters

- glib-macros/tests/properties.rs
- glib/src/param_spec.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/991
> properties: impl HasParamSpec for Vec<String> and StrV

- gio/Gir.toml
- gio/src/auto/list_store.rs
- gio/src/list_model.rs
- gio/src/list_store.rs
- glib/src/boxed_any_object.rs
Makes passing the type more idiomatic.
> gio: Make ListStore::new() take a type parameter

- glib-macros/tests/value_delegate_derive.rs
- glib/src/param_spec.rs
- glib/src/value.rs
depends on https://github.com/gtk-rs/gtk-rs-core/pull/1043 (Of which commits are also included here)
> glib: impl StaticType, FromValue, ToValue, HasParamSpec for Box<str>

- glib/tests/subclass_compiletest/02-no-auto-send-sync.stderr
- glib/tests/subclass_compiletest/03-object-no-auto-send-sync.stderr
- glib/tests/subclass_compiletest/05-no-auto-send-sync-with-non-send-sync-parent.stderr
- glib/tests/subclass_compiletest/06-no-auto-send-sync-with-non-send-sync-ffi-parent.stderr
- pango/src/lib.rs
> Fix CI for rust 1.68

- examples/gio_futures/main.rs
- examples/gio_futures_await/main.rs
- examples/gio_task/file_size/ffi.rs
- examples/gio_task/file_size/mod.rs
- gio/src/input_stream.rs
- gio/src/memory_input_stream.rs
- gio/src/output_stream.rs
- gio/src/pollable_input_stream.rs
- gio/src/pollable_output_stream.rs
- gio/src/subclass/async_initable.rs
- glib/src/future_with_timeout.rs
- glib/src/main_context.rs
- glib/src/main_context_futures.rs
- glib/src/source.rs
- glib/src/source_futures.rs
It makes more sense compared a struct + various constants
> glib: Switch Priority to associated constants

- glib/src/collections/ptr_slice.rs
- glib/src/collections/slice.rs
- glib/src/collections/strv.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1075
> glib: Fix inverted boolean conditions when deciding whether to reserve new space

- gio/src/list_store.rs
- glib-macros/src/variant_derive.rs
- glib-macros/tests/test.rs
- glib/Gir_GObject.toml
- glib/src/enums.rs
- glib/src/gobject/auto/signal_group.rs
- glib/src/gobject/signal_group.rs
- glib/src/param_spec.rs
Follow up to #1032
Also make `ListStore::new` restricted to `Object` types
> Split new/with_type in a few more places

- pango/Gir.toml
> pango: Mark manual impls as such

- glib/src/control_flow.rs
Causes an infinite loop currently
> control flow: Fix logic in From implementation

- .github/dependabot.yml
Similar to what we do in gtk4-rs
> CI: add dependabot for updating the actions

- Dockerfile
rawhide can break pretty badly
> image: Switch to latest fedora stable

- .github/workflows/CI.yml
- deny.toml
> CI: add a cargo deny job

- Cargo.lock
- deny.toml
- glib-macros/Cargo.toml
- glib-macros/src/boxed_derive.rs
- glib-macros/src/closure.rs
- glib-macros/src/derived_properties_attribute.rs
- glib-macros/src/enum_derive.rs
- glib-macros/src/error_domain_derive.rs
- glib-macros/src/lib.rs
- glib-macros/src/object_interface_attribute.rs
- glib-macros/src/object_subclass_attribute.rs
- glib-macros/src/shared_boxed_derive.rs
- glib-macros/src/variant_derive.rs
> Replace usage of macro `proc_macro_error` with explicit propagation of  `syn::Result`

- glib-macros/Cargo.toml
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1300
> glib-macros: Require at least syn 2.0.32

- glib/src/object.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1339
> glib: Freeze property notifications while setting multiple properties

- .github/workflows/CI.yml
> ci: Enable glib-sys / gobject-sys tests

- glib/src/object.rs
Listing all properties of a type needs to iterate over every single pspec that is registered in the process, which is rather slow. In comparison, finding a specific property for a type only requires one or at most number of class hierarchy depth hash table lookups.
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1366
> glib: Don't use `g_object_list_properties()` for setting properties

- examples/Cargo.toml
- examples/README.md
- examples/gio_dbus_register_object/main.rs
- gio/Gir.toml
- gio/src/auto/dbus_connection.rs
- gio/src/dbus_connection.rs
The documentation states that these can be NULL so that you can decide to pass only some of them.
> gio: make DBusConnection::register_object take optional clousures

- gio/Gir.toml
- gio/src/lib.rs
- gio/src/prelude.rs
- gio/src/subprocess_launcher.rs
- gio/src/win32_input_stream.rs
- gio/src/win32_output_stream.rs
> gio: Properly export Win32InputStream / Win32OutputStream traits

- glib/src/main_context.rs
- glib/src/main_context_futures.rs
- glib/src/source_futures.rs
This potentially fixes the race condition in the test that usually happens on beta
> glib: Improve main context tests a bit

- Cargo.toml
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1526
> glib: Add glib-macros / glib 0.20.3 dependency

- gio/src/dbus_connection.rs
- gio/tests/dbus_peer.rs
> gio: Fix order of arguments to g_dbus_connection_register_object_with_closures()

- pango/Gir.toml
- pango/src/auto/font.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1637
> pango: Add bindings for `Font::languages()`

- glib/src/translate.rs
> glib: Implement ToGlibContainerFromSlice for CStr and CString

- Cargo.lock
- glib/src/gstring.rs
- graphene/src/matrix.rs
@bilelmoussaoui Do you think naming (and place) makes sense like this?
> glib: Add bindings for `g_intern_string()` and `g_intern_static_string()` to `GStr`

- glib/src/thread_guard.rs
> glib: Implement Deref/DerefMut for ThreadGuard

- gio/src/file.rs
Fixes https://github.com/gtk-rs/gtk-rs-core/issues/1785
> gio: Make etag in `File::replace_contents_async()` optional

- glib/tests/derive.rs
- glib/tests/regex_compiletest/05-variance.stderr
- glib/tests/subclass_compiletest/02-no-auto-send-sync.stderr
- glib/tests/subclass_compiletest/03-object-no-auto-send-sync.stderr
- glib/tests/subclass_compiletest/05-no-auto-send-sync-with-non-send-sync-parent.stderr
- glib/tests/subclass_compiletest/06-no-auto-send-sync-with-non-send-sync-ffi-parent.stderr
- pango/src/functions.rs
offset+length needs to be less than *or equal* to the total length.
> pango: Fix off-by-one in assertion for `pango::itemize()`
